CREATE TABLE "notifications" (
	"notificationId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"userId" integer NOT NULL,
	"message" text NOT NULL,
	"payload" jsonb NOT NULL DEFAULT '{}',
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"readAt" timestamptz,
	"statusId" integer NOT NULL,
	CONSTRAINT "pk_notifications" PRIMARY KEY("notificationId")
);

CREATE UNIQUE INDEX "ix_notifications_userId" ON "notifications" (
	"userId",
	"statusId"
);

