package lint

import (
	"fmt"
	"strings"

	"github.com/vmkteam/pgdesigner/pkg/pgd"
)

// FixResult describes a single applied fix.
type FixResult struct {
	Code    string
	Path    string
	Message string
}

// Fix applies auto-fixes for the given issues on the project in-place.
// Only fixable issues are processed; non-fixable are silently skipped.
func Fix(p *pgd.Project, issues []Issue) []FixResult {
	var results []FixResult
	for _, issue := range issues {
		r, ok := Rules[issue.Code]
		if !ok || !r.Fixable {
			continue
		}
		if res, applied := applyFix(p, issue); applied {
			results = append(results, res)
		}
	}
	return results
}

func applyFix(p *pgd.Project, issue Issue) (FixResult, bool) {
	switch issue.Code {
	// Column type replacements
	case RulePreferText:
		return fixColumnType(p, issue, "text")
	case RuleAvoidMoney:
		return fixColumnType(p, issue, "numeric")
	case RulePreferTSTZ:
		return fixColumnType(p, issue, "timestamptz")
	case RuleAvoidTimeTZ:
		return fixColumnType(p, issue, "time")
	case RulePreferJsonb:
		return fixColumnType(p, issue, "jsonb")
	case RulePreferIdentity:
		return fixSerialToIdentity(p, issue)

	// Clear default
	case RuleIdentityDefault, RuleGeneratedDefault:
		return fixClearDefault(p, issue)

	// PK nullable
	case RulePKNullable:
		return fixPKNullable(p, issue)

	// Missing FK index
	case RuleMissingFKIndex:
		return fixMissingFKIndex(p, issue)

	// No PK
	case RuleNoPK:
		return fixNoPK(p, issue)

	// FK NO ACTION -> RESTRICT
	case RuleFKNoAction:
		return fixFKNoAction(p, issue)

	// Drop duplicate/redundant index
	case RuleDupIndexCols, RuleOverlapIndex:
		return fixDropIndex(p, issue)

	// Drop duplicate FK
	case RuleDupFK:
		return fixDropFK(p, issue)
	}
	return FixResult{}, false
}

// fixColumnType changes column type to newType. Path format: "schema.table.column".
func fixColumnType(p *pgd.Project, issue Issue, newType string) (FixResult, bool) {
	col := findColumnByPath(p, issue.Path)
	if col == nil {
		return FixResult{}, false
	}
	oldType := col.Type
	col.Type = newType
	col.Length = 0
	col.Precision = 0
	col.Scale = 0
	return FixResult{
		Code:    issue.Code,
		Path:    issue.Path,
		Message: fmt.Sprintf("changed type %s -> %s", oldType, newType),
	}, true
}

// fixSerialToIdentity converts serial/bigserial/smallserial to identity column.
func fixSerialToIdentity(p *pgd.Project, issue Issue) (FixResult, bool) {
	col := findColumnByPath(p, issue.Path)
	if col == nil {
		return FixResult{}, false
	}
	oldType := col.Type
	switch strings.ToLower(col.Type) {
	case "serial", "smallserial":
		col.Type = "integer"
	case "bigserial":
		col.Type = "bigint"
	default:
		return FixResult{}, false
	}
	col.Identity = &pgd.Identity{Generated: "by-default"}
	return FixResult{
		Code:    issue.Code,
		Path:    issue.Path,
		Message: fmt.Sprintf("changed %s -> %s GENERATED BY DEFAULT AS IDENTITY", oldType, col.Type),
	}, true
}

// fixClearDefault removes the default value from a column.
func fixClearDefault(p *pgd.Project, issue Issue) (FixResult, bool) {
	col := findColumnByPath(p, issue.Path)
	if col == nil {
		return FixResult{}, false
	}
	col.Default = ""
	return FixResult{
		Code:    issue.Code,
		Path:    issue.Path,
		Message: "removed default value",
	}, true
}

// fixPKNullable sets NOT NULL on PK columns. Path format: "schema.table.column".
func fixPKNullable(p *pgd.Project, issue Issue) (FixResult, bool) {
	col := findColumnByPath(p, issue.Path)
	if col == nil {
		return FixResult{}, false
	}
	col.Nullable = "false"
	return FixResult{
		Code:    issue.Code,
		Path:    issue.Path,
		Message: "set NOT NULL on PK column",
	}, true
}

// fixMissingFKIndex creates a btree index on FK columns.
// Path format: "schema.table", message contains FK name in quotes.
func fixMissingFKIndex(p *pgd.Project, issue Issue) (FixResult, bool) {
	schema, table := findTableByPath(p, issue.Path)
	if table == nil {
		return FixResult{}, false
	}

	// Extract FK name from message: `FK "fk_name" columns have no matching index`
	fkName := extractQuoted(issue.Message)
	if fkName == "" {
		return FixResult{}, false
	}

	var fk *pgd.ForeignKey
	for i := range table.FKs {
		if table.FKs[i].Name == fkName {
			fk = &table.FKs[i]
			break
		}
	}
	if fk == nil || len(fk.Columns) == 0 {
		return FixResult{}, false
	}

	// Build index
	colNames := make([]string, len(fk.Columns))
	colRefs := make([]pgd.ColRef, len(fk.Columns))
	for i, fc := range fk.Columns {
		colNames[i] = fc.Name
		colRefs[i] = pgd.ColRef{Name: fc.Name}
	}
	idxName := "ix_" + table.Name + "_" + strings.Join(colNames, "_")

	// Check name doesn't already exist
	for _, idx := range schema.Indexes {
		if idx.Name == idxName {
			return FixResult{}, false
		}
	}

	schema.Indexes = append(schema.Indexes, pgd.Index{
		Name:    idxName,
		Table:   table.Name,
		Using:   "btree",
		Columns: colRefs,
	})

	return FixResult{
		Code:    issue.Code,
		Path:    issue.Path,
		Message: fmt.Sprintf("created index %s", idxName),
	}, true
}

// fixNoPK adds an id column with identity and a PK constraint.
// Path format: "schema.table".
func fixNoPK(p *pgd.Project, issue Issue) (FixResult, bool) {
	_, table := findTableByPath(p, issue.Path)
	if table == nil || table.PK != nil {
		return FixResult{}, false
	}

	// Determine PK column name from naming convention
	naming := p.ProjectMeta.Settings.Naming.Convention
	pkColName := "id"
	if names := ExpectedPKName(table.Name, naming); len(names) > 0 {
		pkColName = names[0]
	}

	// Check column name doesn't conflict
	for _, c := range table.Columns {
		if c.Name == pkColName {
			return FixResult{}, false
		}
	}

	// Prepend column
	col := pgd.Column{
		Name:     pkColName,
		Type:     "integer",
		Nullable: "false",
		Identity: &pgd.Identity{Generated: "by-default"},
	}
	table.Columns = append([]pgd.Column{col}, table.Columns...)

	// Add PK
	table.PK = &pgd.PrimaryKey{
		Name:    "pk_" + table.Name,
		Columns: []pgd.ColRef{{Name: pkColName}},
	}

	return FixResult{
		Code:    issue.Code,
		Path:    issue.Path,
		Message: fmt.Sprintf("added PK column %s (integer identity by default)", pkColName),
	}, true
}

// fixFKNoAction changes NO ACTION to RESTRICT on FK.
// Path format: "schema.table", message contains FK name in quotes.
func fixFKNoAction(p *pgd.Project, issue Issue) (FixResult, bool) {
	_, table := findTableByPath(p, issue.Path)
	if table == nil {
		return FixResult{}, false
	}
	fkName := extractQuoted(issue.Message)
	if fkName == "" {
		return FixResult{}, false
	}
	for i := range table.FKs {
		if table.FKs[i].Name == fkName {
			changed := false
			if strings.EqualFold(table.FKs[i].OnDelete, "no action") {
				table.FKs[i].OnDelete = "RESTRICT"
				changed = true
			}
			if strings.EqualFold(table.FKs[i].OnUpdate, "no action") {
				table.FKs[i].OnUpdate = "RESTRICT"
				changed = true
			}
			if changed {
				return FixResult{
					Code:    issue.Code,
					Path:    issue.Path,
					Message: fmt.Sprintf("FK %s: NO ACTION -> RESTRICT", fkName),
				}, true
			}
		}
	}
	return FixResult{}, false
}

// fixDropIndex removes an index by name. Path format: "schema.indexName".
func fixDropIndex(p *pgd.Project, issue Issue) (FixResult, bool) {
	parts := strings.SplitN(issue.Path, ".", 2)
	if len(parts) < 2 {
		return FixResult{}, false
	}
	schemaName, idxName := parts[0], parts[1]
	for i := range p.Schemas {
		if p.Schemas[i].Name != schemaName {
			continue
		}
		for j, idx := range p.Schemas[i].Indexes {
			if idx.Name == idxName {
				p.Schemas[i].Indexes = append(p.Schemas[i].Indexes[:j], p.Schemas[i].Indexes[j+1:]...)
				return FixResult{
					Code:    issue.Code,
					Path:    issue.Path,
					Message: fmt.Sprintf("dropped index %s", idxName),
				}, true
			}
		}
	}
	return FixResult{}, false
}

// fixDropFK removes a duplicate FK by name. Path format: "schema.table".
// FK name is the first quoted string in the message.
func fixDropFK(p *pgd.Project, issue Issue) (FixResult, bool) {
	_, table := findTableByPath(p, issue.Path)
	if table == nil {
		return FixResult{}, false
	}
	fkName := extractQuoted(issue.Message)
	if fkName == "" {
		return FixResult{}, false
	}
	for i, fk := range table.FKs {
		if fk.Name == fkName {
			table.FKs = append(table.FKs[:i], table.FKs[i+1:]...)
			return FixResult{
				Code:    issue.Code,
				Path:    issue.Path,
				Message: fmt.Sprintf("dropped FK %s", fkName),
			}, true
		}
	}
	return FixResult{}, false
}

// --- helpers ---

// findColumnByPath finds a column by "schema.table.column" path.
func findColumnByPath(p *pgd.Project, path string) *pgd.Column {
	parts := strings.SplitN(path, ".", 3)
	if len(parts) != 3 {
		return nil
	}
	_, table := findTableByPath(p, path)
	if table == nil {
		return nil
	}
	colName := parts[2]
	for i := range table.Columns {
		if table.Columns[i].Name == colName {
			return &table.Columns[i]
		}
	}
	return nil
}

// findTableByPath finds a schema and table by "schema.table" path.
func findTableByPath(p *pgd.Project, path string) (*pgd.Schema, *pgd.Table) {
	parts := strings.SplitN(path, ".", 3)
	if len(parts) < 2 {
		return nil, nil
	}
	schemaName, tableName := parts[0], parts[1]
	for i := range p.Schemas {
		if p.Schemas[i].Name != schemaName {
			continue
		}
		for j := range p.Schemas[i].Tables {
			if p.Schemas[i].Tables[j].Name == tableName {
				return &p.Schemas[i], &p.Schemas[i].Tables[j]
			}
		}
	}
	return nil, nil
}

// extractQuoted extracts the first double-quoted string from s.
func extractQuoted(s string) string {
	start := strings.IndexByte(s, '"')
	if start < 0 {
		return ""
	}
	end := strings.IndexByte(s[start+1:], '"')
	if end < 0 {
		return ""
	}
	return s[start+1 : start+1+end]
}
