import api from '@/api/factory'

/**
 * Creates a table with default PK column: {singular}Id integer NN PK GENERATED BY DEFAULT AS IDENTITY.
 * Returns the full table name (with schema prefix if non-default).
 */
export async function createTableWithPK(schemaName: string, tableName: string, defaultSchema: string): Promise<string> {
  await api.project.createTable({ schemaName, tableName })

  const fullName = schemaName !== defaultSchema ? `${schemaName}.${tableName}` : tableName
  const singular = await api.project.singularize({ word: tableName })
  const pkColName = `${singular || tableName}Id`

  await api.project.updateTable({
    name: fullName,
    columns: [{
      name: pkColName, type: 'integer', length: 0, precision: 0, scale: 0,
      nullable: false, default: '', pk: true, fk: false,
      identity: 'by-default', generated: '', generatedStored: false,
      comment: '', compression: '', storage: '', collation: '',
    }],
    pk: { name: `pk_${tableName}`, columns: [pkColName] },
  } as any)

  return fullName
}
