CREATE EXTENSION IF NOT EXISTS "btree_gist";

CREATE TYPE "document_status" AS ENUM ('draft', 'review', 'published', 'archived');

CREATE TYPE "user_role" AS ENUM ('viewer', 'editor', 'admin', 'owner');

CREATE DOMAIN "email_address" AS text CONSTRAINT "email_address_check" CHECK (value ~ E'^[^@]+@[^@]+\\.[^@]+$'::text);

CREATE DOMAIN "positive_int" AS integer CONSTRAINT "positive_int_check" CHECK (value > 0);

CREATE DOMAIN "slug" AS varchar NOT NULL CONSTRAINT "slug_format" CHECK (value::text ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'::text);

CREATE TABLE "audit_log" (
	"id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
	"user_id" bigint,
	"table_name" varchar(64) NOT NULL,
	"record_id" bigint NOT NULL,
	"action" varchar(10) NOT NULL,
	"old_data" jsonb,
	"new_data" jsonb,
	"ip_address" inet,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_audit_log" PRIMARY KEY("id"),
	CONSTRAINT "chk_audit_action" CHECK(action::text = ANY(ARRAY['INSERT'::varchar, 'UPDATE'::varchar, 'DELETE'::varchar]::text[]))
);

CREATE TABLE "booking_slots" (
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"room_name" varchar(100) NOT NULL,
	"booked_during" tstzrange NOT NULL,
	"booked_by" bigint NOT NULL,
	CONSTRAINT "pk_booking_slots" PRIMARY KEY("id")
);

CREATE TABLE "categories" (
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"parent_id" integer,
	"name" varchar(100) NOT NULL,
	"slug" slug,
	"description" text,
	"sort_order" positive_int DEFAULT 1,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_categories" PRIMARY KEY("id")
);

CREATE TABLE "document_permissions" (
	"id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
	"document_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"role" user_role NOT NULL DEFAULT 'viewer'::public.user_role,
	"granted_at" timestamptz NOT NULL DEFAULT now(),
	"expires_at" timestamptz,
	CONSTRAINT "pk_document_permissions" PRIMARY KEY("id"),
	CONSTRAINT "uq_docperm_document_user" UNIQUE("document_id", "user_id"),
	CONSTRAINT "chk_docperm_expires" CHECK(expires_at IS NULL OR expires_at > granted_at)
);

CREATE TABLE "document_tags" (
	"document_id" bigint NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "pk_document_tags" PRIMARY KEY("document_id", "tag_id")
);

CREATE TABLE "documents" (
	"id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
	"category_id" integer,
	"author_id" bigint NOT NULL,
	"title" varchar(500) NOT NULL,
	"body" text,
	"metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
	"tags" text[] NOT NULL DEFAULT '{}'::text[],
	"status" document_status NOT NULL DEFAULT 'draft'::public.document_status,
	"version" positive_int NOT NULL DEFAULT 1,
	"search_vector" tsvector,
	"published_at" timestamptz,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"updated_at" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_documents" PRIMARY KEY("id"),
	CONSTRAINT "chk_documents_publish" CHECK(status <> 'published'::public.document_status OR published_at IS NOT NULL)
);

CREATE TABLE "tags" (
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(60) NOT NULL,
	"color" bpchar DEFAULT '#cccccc'::bpchar,
	CONSTRAINT "pk_tags" PRIMARY KEY("id"),
	CONSTRAINT "uq_tags_name" UNIQUE("name"),
	CONSTRAINT "chk_tags_color" CHECK(color ~ '^#[0-9a-fA-F]{6}$'::text)
);

CREATE TABLE "users" (
	"id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
	"email" email_address NOT NULL,
	"display_name" varchar(200) NOT NULL,
	"role" user_role NOT NULL DEFAULT 'viewer'::public.user_role,
	"settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
	"tags" text[] NOT NULL DEFAULT '{}'::text[],
	"search_vector" tsvector,
	"is_active" boolean NOT NULL DEFAULT true,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"updated_at" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_users" PRIMARY KEY("id"),
	CONSTRAINT "uq_users_email" UNIQUE("email")
);

CREATE INDEX "idx_audit_created" ON "audit_log" (
	"created_at" DESC
);

CREATE INDEX "idx_audit_new_data_gin" ON "audit_log" USING GIN (
	"new_data"
);

CREATE INDEX "idx_audit_old_data_gin" ON "audit_log" USING GIN (
	"old_data"
);

CREATE INDEX "idx_audit_recent" ON "audit_log" (
	"created_at" DESC
)
	WHERE created_at > '2024-01-01 00:00:00+03'::timestamp with time zone;

CREATE INDEX "idx_audit_table_record" ON "audit_log" (
	"table_name",
	"record_id"
);

CREATE INDEX "idx_categories_parent" ON "categories" (
	"parent_id"
);

CREATE INDEX "idx_categories_slug_lower" ON "categories" (
	(lower(slug::text))
);

CREATE INDEX "idx_documents_active" ON "documents" (
	"created_at" DESC
)
	WHERE status = 'published'::public.document_status;

CREATE INDEX "idx_documents_author" ON "documents" (
	"author_id"
);

CREATE INDEX "idx_documents_category" ON "documents" (
	"category_id"
);

CREATE INDEX "idx_documents_draft" ON "documents" (
	"author_id",
	"updated_at" DESC
)
	WHERE status = 'draft'::public.document_status;

CREATE INDEX "idx_documents_metadata_gin" ON "documents" USING GIN (
	"metadata"
);

CREATE INDEX "idx_documents_search_gist" ON "documents" USING GIST (
	"search_vector"
);

CREATE INDEX "idx_documents_status" ON "documents" (
	"status"
);

CREATE INDEX "idx_documents_tags_gin" ON "documents" USING GIN (
	"tags"
);

CREATE INDEX "idx_documents_title_lower" ON "documents" (
	(lower(title::text))
);

CREATE INDEX "idx_users_active" ON "users" (
	"email"
)
	WHERE is_active = true;

CREATE INDEX "idx_users_email_lower" ON "users" (
	(lower(email::text))
);

CREATE INDEX "idx_users_search_gist" ON "users" USING GIST (
	"search_vector"
);

CREATE INDEX "idx_users_settings_gin" ON "users" USING GIN (
	"settings"
);

CREATE INDEX "idx_users_tags_gin" ON "users" USING GIN (
	"tags"
);

ALTER TABLE "audit_log" ADD CONSTRAINT "fk_audit_user" FOREIGN KEY ("user_id")
	REFERENCES "users"("id")
	ON DELETE SET NULL
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "booking_slots" ADD CONSTRAINT "fk_booking_user" FOREIGN KEY ("booked_by")
	REFERENCES "users"("id")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "categories" ADD CONSTRAINT "fk_categories_parent" FOREIGN KEY ("parent_id")
	REFERENCES "categories"("id")
	ON DELETE SET NULL
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "document_permissions" ADD CONSTRAINT "fk_docperm_document" FOREIGN KEY ("document_id")
	REFERENCES "documents"("id")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "document_permissions" ADD CONSTRAINT "fk_docperm_user" FOREIGN KEY ("user_id")
	REFERENCES "users"("id")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "document_tags" ADD CONSTRAINT "fk_doctags_document" FOREIGN KEY ("document_id")
	REFERENCES "documents"("id")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "document_tags" ADD CONSTRAINT "fk_doctags_tag" FOREIGN KEY ("tag_id")
	REFERENCES "tags"("id")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "documents" ADD CONSTRAINT "fk_documents_author" FOREIGN KEY ("author_id")
	REFERENCES "users"("id")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "documents" ADD CONSTRAINT "fk_documents_category" FOREIGN KEY ("category_id")
	REFERENCES "categories"("id")
	ON DELETE SET NULL
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

CREATE OR REPLACE FUNCTION "audit_trigger_func"()
RETURNS trigger
LANGUAGE plpgsql
AS $FUNCTION$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit_log (user_id, table_name, record_id, action, new_data)
        VALUES (current_setting('app.current_user_id', true)::bigint, TG_TABLE_NAME, NEW.id, TG_OP, to_jsonb(NEW));
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO audit_log (user_id, table_name, record_id, action, old_data, new_data)
        VALUES (current_setting('app.current_user_id', true)::bigint, TG_TABLE_NAME, NEW.id, TG_OP, to_jsonb(OLD), to_jsonb(NEW));
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO audit_log (user_id, table_name, record_id, action, old_data)
        VALUES (current_setting('app.current_user_id', true)::bigint, TG_TABLE_NAME, OLD.id, TG_OP, to_jsonb(OLD));
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$FUNCTION$;

CREATE OR REPLACE FUNCTION "update_document_search_vector"()
RETURNS trigger
LANGUAGE plpgsql
AS $FUNCTION$
BEGIN
    NEW.search_vector := to_tsvector('english', coalesce(NEW.title, '') || ' ' || coalesce(NEW.body, ''));
    RETURN NEW;
END;
$FUNCTION$;

CREATE OR REPLACE FUNCTION "update_user_search_vector"()
RETURNS trigger
LANGUAGE plpgsql
AS $FUNCTION$
BEGIN
    NEW.search_vector := to_tsvector('english', coalesce(NEW.display_name, '') || ' ' || coalesce(NEW.email::text, ''));
    RETURN NEW;
END;
$FUNCTION$;

CREATE TRIGGER "trg_documents_audit"
	AFTER INSERT OR DELETE OR UPDATE
	ON "documents"
	FOR EACH ROW
	EXECUTE FUNCTION "audit_trigger_func"();

CREATE TRIGGER "trg_documents_search_vector"
	BEFORE INSERT OR UPDATE
	ON "documents"
	FOR EACH ROW
	EXECUTE FUNCTION "update_document_search_vector"();

CREATE TRIGGER "trg_users_audit"
	AFTER INSERT OR DELETE OR UPDATE
	ON "users"
	FOR EACH ROW
	EXECUTE FUNCTION "audit_trigger_func"();

CREATE TRIGGER "trg_users_search_vector"
	BEFORE INSERT OR UPDATE
	ON "users"
	FOR EACH ROW
	EXECUTE FUNCTION "update_user_search_vector"();

COMMENT ON TABLE "audit_log" IS 'Immutable audit trail for all data changes';
COMMENT ON COLUMN "audit_log"."old_data" IS 'Previous row state as JSON (NULL for INSERT)';
COMMENT ON COLUMN "audit_log"."new_data" IS 'New row state as JSON (NULL for DELETE)';
COMMENT ON TABLE "booking_slots" IS 'Room booking with non-overlapping time range constraint';
COMMENT ON COLUMN "booking_slots"."booked_during" IS 'Time range for the booking (tstzrange with EXCLUDE constraint)';
COMMENT ON TABLE "categories" IS 'Hierarchical document categories (self-referencing tree)';
COMMENT ON TABLE "document_permissions" IS 'Per-document user permissions with optional expiration';
COMMENT ON TABLE "document_tags" IS 'Many-to-many relationship between documents and tags';
COMMENT ON TABLE "documents" IS 'Core document storage with full-text search and versioning';
COMMENT ON COLUMN "documents"."metadata" IS 'Arbitrary document metadata as JSON (custom fields, etc.)';
COMMENT ON COLUMN "documents"."version" IS 'Monotonically increasing version number';
COMMENT ON COLUMN "documents"."search_vector" IS 'Full-text search index over title and body';
COMMENT ON TABLE "tags" IS 'Flat tag taxonomy for document classification';
COMMENT ON TABLE "users" IS 'System users with role-based access control';
COMMENT ON COLUMN "users"."settings" IS 'User preferences as JSON (theme, notifications, etc.)';
COMMENT ON COLUMN "users"."tags" IS 'Free-form text tags for user categorization';
COMMENT ON COLUMN "users"."search_vector" IS 'Full-text search index over display_name and email';
COMMENT ON INDEX "idx_documents_active" IS 'Partial index: only published documents';
COMMENT ON INDEX "idx_documents_metadata_gin" IS 'GIN index for JSONB containment queries on document metadata';
COMMENT ON INDEX "idx_documents_search_gist" IS 'GiST index for full-text search on documents';
COMMENT ON INDEX "idx_users_settings_gin" IS 'GIN index for JSONB containment queries on user settings';
