package sql

import (
	"encoding/xml"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/vmkteam/pgdesigner/pkg/pgd"
)

func TestParseSQL_Golden(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		golden  string
		project string
		tables  int
		fks     int
		indexes int
	}{
		{"chinook", "testdata/chinook.sql", "testdata/chinook.pgd", "chinook", 11, 11, 11},
		{"northwind", "testdata/northwind.sql", "testdata/northwind.pgd", "northwind", 14, 13, 0},
		{"pagila", "testdata/pagila.sql", "testdata/pagila.pgd", "pagila", 15, 18, 16},
		{"airlines", "testdata/airlines.sql", "testdata/airlines.pgd", "airlines", 8, 8, 0},
		{"adventureworks", "testdata/adventureworks.sql", "testdata/adventureworks.pgd", "adventureworks", 68, 89, 2},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := os.ReadFile(tt.input)
			require.NoError(t, err)

			p, err := ParseSQL(string(data), tt.project)
			require.NoError(t, err)

			got, err := xml.MarshalIndent(p, "", "  ")
			require.NoError(t, err)
			got = []byte(xml.Header + string(got) + "\n")

			want, err := os.ReadFile(tt.golden)
			require.NoError(t, err)

			assert.Equal(t, string(want), string(got), "golden mismatch for %s", tt.golden)

			// object counts across all schemas
			var tableCount, fkCount, indexCount int
			for _, schema := range p.Schemas {
				tableCount += len(schema.Tables)
				indexCount += len(schema.Indexes)
				for _, tbl := range schema.Tables {
					fkCount += len(tbl.FKs)
				}
			}
			assert.Equal(t, tt.tables, tableCount, "table count")
			assert.Equal(t, tt.fks, fkCount, "FK count")
			assert.Equal(t, tt.indexes, indexCount, "index count")
		})
	}
}

func TestParseSQL_RoundTrip(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		project string
	}{
		{"chinook", "testdata/chinook.sql", "chinook"},
		{"northwind", "testdata/northwind.sql", "northwind"},
		{"pagila", "testdata/pagila.sql", "pagila"},
		{"airlines", "testdata/airlines.sql", "airlines"},
		{"adventureworks", "testdata/adventureworks.sql", "adventureworks"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := os.ReadFile(tt.input)
			require.NoError(t, err)

			p, err := ParseSQL(string(data), tt.project)
			require.NoError(t, err)

			// marshal → unmarshal → marshal
			out1, err := xml.MarshalIndent(p, "", "  ")
			require.NoError(t, err)

			var p2 pgd.Project
			require.NoError(t, xml.Unmarshal(out1, &p2))

			out2, err := xml.MarshalIndent(&p2, "", "  ")
			require.NoError(t, err)

			assert.Equal(t, string(out1), string(out2), "round-trip mismatch")
		})
	}
}

func TestParseSQL_GeneratedDDL(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		golden  string
		project string
		tables  int
		indexes int
		fks     int
	}{
		{"chinook", "testdata/chinook.sql", "testdata/chinook_generated.sql", "chinook", 11, 11, 11},
		{"northwind", "testdata/northwind.sql", "testdata/northwind_generated.sql", "northwind", 14, 0, 13},
		{"pagila", "testdata/pagila.sql", "testdata/pagila_generated.sql", "pagila", 22, 16, 18},
		{"airlines", "testdata/airlines.sql", "testdata/airlines_generated.sql", "airlines", 8, 0, 8},
		{"adventureworks", "testdata/adventureworks.sql", "testdata/adventureworks_generated.sql", "adventureworks", 68, 2, 89},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := os.ReadFile(tt.input)
			require.NoError(t, err)

			p, err := ParseSQL(string(data), tt.project)
			require.NoError(t, err)

			ddl := pgd.GenerateDDL(p)

			want, err := os.ReadFile(tt.golden)
			require.NoError(t, err)

			assert.Equal(t, string(want), ddl, "DDL mismatch with %s", tt.golden)

			// object counts in generated DDL
			assert.Equal(t, tt.tables, strings.Count(ddl, "CREATE TABLE "), "tables")
			assert.Equal(t, tt.indexes, strings.Count(ddl, "CREATE INDEX ")+strings.Count(ddl, "CREATE UNIQUE INDEX "), "indexes")
			assert.Equal(t, tt.fks, strings.Count(ddl, "ALTER TABLE"), "FKs")
		})
	}
}

func TestParseSQL_ColumnTypes(t *testing.T) {
	sql := `CREATE TABLE "test" (
		"a" integer NOT NULL,
		"b" varchar(100),
		"c" numeric(12, 2) NOT NULL,
		"d" boolean DEFAULT false,
		"e" timestamptz NOT NULL DEFAULT now(),
		"f" jsonb,
		"g" text[],
		"h" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
		"i" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
		PRIMARY KEY("a")
	);`

	p, err := ParseSQL(sql, "test")
	require.NoError(t, err)

	tbl := p.Schemas[0].Tables[0]
	require.Len(t, tbl.Columns, 9)

	// integer NOT NULL
	assert.Equal(t, "integer", tbl.Columns[0].Type)
	assert.Equal(t, "false", tbl.Columns[0].Nullable)

	// varchar(100)
	assert.Equal(t, "varchar", tbl.Columns[1].Type)
	assert.Equal(t, 100, tbl.Columns[1].Length)

	// numeric(12,2)
	assert.Equal(t, "numeric", tbl.Columns[2].Type)
	assert.Equal(t, 12, tbl.Columns[2].Precision)
	assert.Equal(t, 2, tbl.Columns[2].Scale)

	// boolean DEFAULT false
	assert.Equal(t, "boolean", tbl.Columns[3].Type)
	assert.Equal(t, "false", tbl.Columns[3].Default)

	// timestamptz NOT NULL DEFAULT now()
	assert.Equal(t, "timestamptz", tbl.Columns[4].Type)
	assert.Equal(t, "false", tbl.Columns[4].Nullable)
	assert.Equal(t, "now()", tbl.Columns[4].Default)

	// jsonb
	assert.Equal(t, "jsonb", tbl.Columns[5].Type)

	// text[]
	assert.Equal(t, "text[]", tbl.Columns[6].Type)

	// GENERATED BY DEFAULT AS IDENTITY
	require.NotNil(t, tbl.Columns[7].Identity)
	assert.Equal(t, "by-default", tbl.Columns[7].Identity.Generated)

	// GENERATED ALWAYS AS IDENTITY
	require.NotNil(t, tbl.Columns[8].Identity)
	assert.Equal(t, "always", tbl.Columns[8].Identity.Generated)
}

func TestParseSQL_Constraints(t *testing.T) {
	sql := `
	CREATE TABLE "statuses" (
		"statusId" integer NOT NULL,
		"alias" varchar(64) NOT NULL,
		PRIMARY KEY("statusId"),
		UNIQUE("alias")
	);
	CREATE TABLE "users" (
		"userId" integer NOT NULL,
		"statusId" integer NOT NULL,
		PRIMARY KEY("userId"),
		CONSTRAINT "chk_positive" CHECK("userId" > 0)
	);
	ALTER TABLE "users" ADD FOREIGN KEY ("statusId")
		REFERENCES "statuses"("statusId")
		ON DELETE RESTRICT ON UPDATE CASCADE NOT DEFERRABLE;
	`

	p, err := ParseSQL(sql, "test")
	require.NoError(t, err)

	statuses := p.Schemas[0].Tables[0]
	require.NotNil(t, statuses.PK)
	assert.Len(t, statuses.PK.Columns, 1)
	assert.Len(t, statuses.Uniques, 1)

	users := p.Schemas[0].Tables[1]
	require.NotNil(t, users.PK)
	require.Len(t, users.Checks, 1)
	assert.Equal(t, "chk_positive", users.Checks[0].Name)

	require.Len(t, users.FKs, 1)
	fk := users.FKs[0]
	assert.Equal(t, "statuses", fk.ToTable)
	assert.Equal(t, "restrict", fk.OnDelete)
	assert.Equal(t, "cascade", fk.OnUpdate)
	assert.Len(t, fk.Columns, 1)
	assert.Equal(t, "statusId", fk.Columns[0].Name)
	assert.Equal(t, "statusId", fk.Columns[0].References)
}

func TestParseSQL_Indexes(t *testing.T) {
	sql := `
	CREATE TABLE "users" ("email" text, "data" jsonb, "active" boolean);
	CREATE UNIQUE INDEX "idx_email" ON "users" ("email");
	CREATE INDEX "idx_data" ON "users" USING GIN ("data");
	CREATE INDEX "idx_active" ON "users" ("email") WHERE "active" = true;
	CREATE INDEX "idx_lower" ON "users" ((lower("email")));
	CREATE INDEX "idx_desc" ON "users" ("email" DESC NULLS LAST);
	`

	p, err := ParseSQL(sql, "test")
	require.NoError(t, err)

	idxs := p.Schemas[0].Indexes
	require.Len(t, idxs, 5)

	// Find indexes by name (sorted alphabetically)
	idxMap := map[string]int{}
	for i, idx := range idxs {
		idxMap[idx.Name] = i
	}

	// unique
	assert.Equal(t, "true", idxs[idxMap["idx_email"]].Unique)

	// GIN
	assert.Equal(t, "gin", idxs[idxMap["idx_data"]].Using)

	// WHERE
	require.NotNil(t, idxs[idxMap["idx_active"]].Where)
	assert.Contains(t, idxs[idxMap["idx_active"]].Where.Value, "active", "WHERE should reference active")

	// expression index
	ei := idxs[idxMap["idx_lower"]]
	assert.True(t, len(ei.Expressions) > 0 || len(ei.Columns) > 0, "should parse expression index")

	// DESC NULLS LAST
	di := idxs[idxMap["idx_desc"]]
	if len(di.Columns) > 0 {
		assert.Equal(t, "desc", di.Columns[0].Order)
		assert.Equal(t, "last", di.Columns[0].Nulls)
	}
}

func TestParseSQL_Serial(t *testing.T) {
	sql := `CREATE TABLE "t" (
		"id" SERIAL NOT NULL,
		"bigId" BIGSERIAL NOT NULL,
		PRIMARY KEY("id")
	);`

	p, err := ParseSQL(sql, "test")
	require.NoError(t, err)

	// SERIAL stays as serial type (valid in model, DDL generator handles it)
	assert.Equal(t, "serial", p.Schemas[0].Tables[0].Columns[0].Type)
	assert.Equal(t, "false", p.Schemas[0].Tables[0].Columns[0].Nullable)
	assert.Equal(t, "bigserial", p.Schemas[0].Tables[0].Columns[1].Type)
}
