// Code generated by colgen v0.1.3; DO NOT EDIT.
package rpc

import (
	"github.com/vmkteam/pgdesigner/pkg/designer/diff"
	"github.com/vmkteam/pgdesigner/pkg/designer/lint"
	"github.com/vmkteam/pgdesigner/pkg/pgd"
)

func NewDiffChanges(in []diff.Change) []DiffChange { return MapP(in, NewDiffChange) }

func NewDiffHazards(in []diff.Hazard) []DiffHazard { return MapP(in, NewDiffHazard) }

func NewERDColumns(in []pgd.ERDColumn) []ERDColumn { return MapP(in, NewERDColumn) }

func NewERDIndices(in []pgd.ERDIndex) []ERDIndex { return MapP(in, NewERDIndex) }

func NewERDReferences(in []pgd.ERDReference) []ERDReference { return MapP(in, NewERDReference) }

func NewERDTables(in []pgd.ERDTable) []ERDTable { return MapP(in, NewERDTable) }

func NewLintIssues(in []lint.Issue) []LintIssue { return MapP(in, NewLintIssue) }
