// Code generated by zenrpc v2.3.2; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	AppService     struct{ Quit, Ping, About string }
	ProjectService struct{ GetInfo, GetSchema, GetDDL, Lint, ListObjects, GetTable, SaveProject, SaveLayout, IsDirty, GetAutoSave, SetAutoSave, ListTypes, UpdateTable, PreviewDiff, DiffUnsaved, FixLintIssues, IgnoreLintRules, GetIgnoredRules, UnignoreLintRules, CreateTable, DeleteTable, CreateSchema, DeleteSchema, MoveTable, GetProjectSettings, UpdateProjectSettings, LintTable string }
}{
	AppService: struct{ Quit, Ping, About string }{
		Quit:  "quit",
		Ping:  "ping",
		About: "about",
	},
	ProjectService: struct{ GetInfo, GetSchema, GetDDL, Lint, ListObjects, GetTable, SaveProject, SaveLayout, IsDirty, GetAutoSave, SetAutoSave, ListTypes, UpdateTable, PreviewDiff, DiffUnsaved, FixLintIssues, IgnoreLintRules, GetIgnoredRules, UnignoreLintRules, CreateTable, DeleteTable, CreateSchema, DeleteSchema, MoveTable, GetProjectSettings, UpdateProjectSettings, LintTable string }{
		GetInfo:               "getinfo",
		GetSchema:             "getschema",
		GetDDL:                "getddl",
		Lint:                  "lint",
		ListObjects:           "listobjects",
		GetTable:              "gettable",
		SaveProject:           "saveproject",
		SaveLayout:            "savelayout",
		IsDirty:               "isdirty",
		GetAutoSave:           "getautosave",
		SetAutoSave:           "setautosave",
		ListTypes:             "listtypes",
		UpdateTable:           "updatetable",
		PreviewDiff:           "previewdiff",
		DiffUnsaved:           "diffunsaved",
		FixLintIssues:         "fixlintissues",
		IgnoreLintRules:       "ignorelintrules",
		GetIgnoredRules:       "getignoredrules",
		UnignoreLintRules:     "unignorelintrules",
		CreateTable:           "createtable",
		DeleteTable:           "deletetable",
		CreateSchema:          "createschema",
		DeleteSchema:          "deleteschema",
		MoveTable:             "movetable",
		GetProjectSettings:    "getprojectsettings",
		UpdateProjectSettings: "updateprojectsettings",
		LintTable:             "linttable",
	},
}

func (AppService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Quit": {
				Description: `Quit starts a delayed shutdown. If Ping is not called within the grace period, the server exits.

zenrpc`,
				Parameters: []smd.JSONSchema{},
			},
			"Ping": {
				Description: `Ping cancels a pending shutdown (e.g. after page reload).

zenrpc`,
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type: smd.String,
				},
			},
			"About": {
				Description: `About returns application metadata.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `AboutInfo`,
					Type:        smd.Object,
					TypeName:    "AboutInfo",
					Properties: smd.PropertyList{
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name: "version",
							Type: smd.String,
						},
						{
							Name: "goVersion",
							Type: smd.String,
						},
						{
							Name: "target",
							Type: smd.String,
						},
						{
							Name: "author",
							Type: smd.String,
						},
						{
							Name: "license",
							Type: smd.String,
						},
						{
							Name: "github",
							Type: smd.String,
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s AppService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}

	switch method {
	case RPC.AppService.Quit:
		s.Quit()

	case RPC.AppService.Ping:
		resp.Set(s.Ping())

	case RPC.AppService.About:
		resp.Set(s.About())

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (ProjectService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"GetInfo": {
				Description: `GetInfo returns project metadata.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `ProjectInfo`,
					Type:        smd.Object,
					TypeName:    "ProjectInfo",
					Properties: smd.PropertyList{
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "pgVersion",
							Type: smd.String,
						},
						{
							Name: "tables",
							Type: smd.Integer,
						},
						{
							Name: "references",
							Type: smd.Integer,
						},
						{
							Name: "indexes",
							Type: smd.Integer,
						},
						{
							Name: "autoSave",
							Type: smd.Boolean,
						},
						{
							Name: "schemas",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "defaultNullable",
							Type: smd.Boolean,
						},
					},
				},
			},
			"GetSchema": {
				Description: `GetSchema returns the ERD schema for rendering in the frontend.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `ERDSchema`,
					Type:        smd.Object,
					TypeName:    "ERDSchema",
					Properties: smd.PropertyList{
						{
							Name: "tables",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/ERDTable",
							},
						},
						{
							Name: "references",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/ERDReference",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"ERDTable": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "schema",
									Type: smd.String,
								},
								{
									Name: "x",
									Type: smd.Integer,
								},
								{
									Name: "y",
									Type: smd.Integer,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/ERDColumn",
									},
								},
								{
									Name: "indexes",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/ERDIndex",
									},
								},
								{
									Name: "partitioned",
									Type: smd.Boolean,
								},
								{
									Name: "partitionCount",
									Type: smd.Integer,
								},
							},
						},
						"ERDColumn": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "type",
									Type: smd.String,
								},
								{
									Name: "pk",
									Type: smd.Boolean,
								},
								{
									Name: "nn",
									Type: smd.Boolean,
								},
								{
									Name: "fk",
									Type: smd.Boolean,
								},
								{
									Name: "default",
									Type: smd.String,
								},
							},
						},
						"ERDIndex": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
							},
						},
						"ERDReference": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "from",
									Type: smd.String,
								},
								{
									Name: "fromCol",
									Type: smd.String,
								},
								{
									Name: "to",
									Type: smd.String,
								},
								{
									Name: "toCol",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"GetDDL": {
				Description: `GetDDL returns the full DDL for the project.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `string`,
					Type:        smd.String,
				},
			},
			"Lint": {
				Description: `Lint validates the project and returns lint issues.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]LintIssue`,
					Type:        smd.Array,
					TypeName:    "[]LintIssue",
					Items: map[string]string{
						"$ref": "#/definitions/LintIssue",
					},
					Definitions: map[string]smd.Definition{
						"LintIssue": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "severity",
									Type: smd.String,
								},
								{
									Name: "code",
									Type: smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "path",
									Type: smd.String,
								},
								{
									Name: "message",
									Type: smd.String,
								},
								{
									Name: "fixable",
									Type: smd.Boolean,
								},
							},
						},
					},
				},
			},
			"ListObjects": {
				Description: `ListObjects returns a flat list of all database objects for Go-To search.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]ObjectItem`,
					Type:        smd.Array,
					TypeName:    "[]ObjectItem",
					Items: map[string]string{
						"$ref": "#/definitions/ObjectItem",
					},
					Definitions: map[string]smd.Definition{
						"ObjectItem": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name:        "kind",
									Description: `table, column, index, fk, pk, unique, check, trigger, sequence, view, function, extension, domain, enum`,
									Type:        smd.String,
								},
								{
									Name:        "table",
									Description: `parent table name (for focusing on canvas)`,
									Type:        smd.String,
								},
							},
						},
					},
				},
			},
			"GetTable": {
				Description: `GetTable returns full table data for the Table Editor.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `table name`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `TableDetail`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "TableDetail",
					Properties: smd.PropertyList{
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "schema",
							Type: smd.String,
						},
						{
							Name: "unlogged",
							Type: smd.Boolean,
						},
						{
							Name: "tablespace",
							Type: smd.String,
						},
						{
							Name: "comment",
							Type: smd.String,
						},
						{
							Name: "columns",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/ColumnDetail",
							},
						},
						{
							Name:     "pk",
							Optional: true,
							Ref:      "#/definitions/PKDetail",
							Type:     smd.Object,
						},
						{
							Name: "uniques",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/UniqueDetail",
							},
						},
						{
							Name: "checks",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/CheckDetail",
							},
						},
						{
							Name: "excludes",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/ExcludeDetail",
							},
						},
						{
							Name: "fks",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/FKDetail",
							},
						},
						{
							Name: "indexes",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/IndexDetail",
							},
						},
						{
							Name:     "partitionBy",
							Optional: true,
							Ref:      "#/definitions/PartitionByRPC",
							Type:     smd.Object,
						},
						{
							Name: "partitions",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/PartitionRPC",
							},
						},
						{
							Name: "ddl",
							Type: smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"ColumnDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "type",
									Type: smd.String,
								},
								{
									Name: "length",
									Type: smd.Integer,
								},
								{
									Name: "precision",
									Type: smd.Integer,
								},
								{
									Name: "scale",
									Type: smd.Integer,
								},
								{
									Name: "nullable",
									Type: smd.Boolean,
								},
								{
									Name: "default",
									Type: smd.String,
								},
								{
									Name: "pk",
									Type: smd.Boolean,
								},
								{
									Name: "fk",
									Type: smd.Boolean,
								},
								{
									Name: "identity",
									Type: smd.String,
								},
								{
									Name:     "identitySeqOpt",
									Optional: true,
									Ref:      "#/definitions/IdentitySeqOpt",
									Type:     smd.Object,
								},
								{
									Name: "generated",
									Type: smd.String,
								},
								{
									Name: "generatedStored",
									Type: smd.Boolean,
								},
								{
									Name: "comment",
									Type: smd.String,
								},
								{
									Name: "compression",
									Type: smd.String,
								},
								{
									Name: "storage",
									Type: smd.String,
								},
								{
									Name: "collation",
									Type: smd.String,
								},
							},
						},
						"IdentitySeqOpt": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "start",
									Type: smd.Integer,
								},
								{
									Name: "increment",
									Type: smd.Integer,
								},
								{
									Name: "min",
									Type: smd.Integer,
								},
								{
									Name: "max",
									Type: smd.Integer,
								},
								{
									Name: "cache",
									Type: smd.Integer,
								},
								{
									Name: "cycle",
									Type: smd.Boolean,
								},
							},
						},
						"PKDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
							},
						},
						"UniqueDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "nullsDistinct",
									Type: smd.Boolean,
								},
							},
						},
						"CheckDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "expression",
									Type: smd.String,
								},
							},
						},
						"ExcludeDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "using",
									Type: smd.String,
								},
								{
									Name: "elements",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/ExcludeElementDetail",
									},
								},
							},
						},
						"ExcludeElementDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "column",
									Type: smd.String,
								},
								{
									Name: "with",
									Type: smd.String,
								},
							},
						},
						"FKDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "toTable",
									Type: smd.String,
								},
								{
									Name: "onDelete",
									Type: smd.String,
								},
								{
									Name: "onUpdate",
									Type: smd.String,
								},
								{
									Name: "deferrable",
									Type: smd.Boolean,
								},
								{
									Name: "initially",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/FKColDetail",
									},
								},
							},
						},
						"FKColDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "references",
									Type: smd.String,
								},
							},
						},
						"IndexDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "unique",
									Type: smd.Boolean,
								},
								{
									Name: "nullsDistinct",
									Type: smd.Boolean,
								},
								{
									Name: "using",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/IndexColDetail",
									},
								},
								{
									Name: "expressions",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "where",
									Type: smd.String,
								},
								{
									Name: "include",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
							},
						},
						"IndexColDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name:        "order",
									Description: `asc|desc`,
									Type:        smd.String,
								},
								{
									Name:        "nulls",
									Description: `first|last`,
									Type:        smd.String,
								},
								{
									Name: "opclass",
									Type: smd.String,
								},
							},
						},
						"PartitionByRPC": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:        "type",
									Description: `range | list | hash`,
									Type:        smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
							},
						},
						"PartitionRPC": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "bound",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "Not Found",
				},
			},
			"SaveProject": {
				Description: `SaveProject writes the project to the .pgd file.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"SaveLayout": {
				Description: `SaveLayout updates table positions in the default layout.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "positions",
						Description: `table positions`,
						Type:        smd.Array,
						TypeName:    "[]LayoutPosition",
						Items: map[string]string{
							"$ref": "#/definitions/LayoutPosition",
						},
						Definitions: map[string]smd.Definition{
							"LayoutPosition": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "schema",
										Type: smd.String,
									},
									{
										Name: "x",
										Type: smd.Integer,
									},
									{
										Name: "y",
										Type: smd.Integer,
									},
								},
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"IsDirty": {
				Description: `IsDirty reports whether the project has unsaved changes.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"GetAutoSave": {
				Description: `GetAutoSave reports whether auto-save is enabled.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"SetAutoSave": {
				Description: `SetAutoSave enables or disables auto-save after each mutation.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "enabled",
						Description: `auto-save flag`,
						Type:        smd.Boolean,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"ListTypes": {
				Description: `ListTypes returns available column types for autocomplete.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]TypeInfo`,
					Type:        smd.Array,
					TypeName:    "[]TypeInfo",
					Items: map[string]string{
						"$ref": "#/definitions/TypeInfo",
					},
					Definitions: map[string]smd.Definition{
						"TypeInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name:        "category",
									Description: `numeric, character, datetime, boolean, json, network, geometric, search, array, enum, composite, domain, system, other`,
									Type:        smd.String,
								},
								{
									Name:        "source",
									Description: `builtin, user`,
									Type:        smd.String,
								},
							},
						},
					},
				},
			},
			"UpdateTable": {
				Description: `UpdateTable applies changes to a table. Each section is optional (null = skip).`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `qualified table name`,
						Type:        smd.String,
					},
					{
						Name:        "general",
						Optional:    true,
						Description: `table properties`,
						Type:        smd.Object,
						TypeName:    "GeneralInput",
						Properties: smd.PropertyList{
							{
								Name:     "name",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "comment",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "unlogged",
								Optional: true,
								Type:     smd.Boolean,
							},
							{
								Name:     "generate",
								Optional: true,
								Type:     smd.Boolean,
							},
						},
					},
					{
						Name:        "columns",
						Description: `full column list replacement`,
						Type:        smd.Array,
						TypeName:    "[]ColumnInput",
						Items: map[string]string{
							"$ref": "#/definitions/ColumnInput",
						},
						Definitions: map[string]smd.Definition{
							"ColumnInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "type",
										Type: smd.String,
									},
									{
										Name: "length",
										Type: smd.Integer,
									},
									{
										Name: "precision",
										Type: smd.Integer,
									},
									{
										Name: "scale",
										Type: smd.Integer,
									},
									{
										Name: "nullable",
										Type: smd.Boolean,
									},
									{
										Name: "default",
										Type: smd.String,
									},
									{
										Name: "identity",
										Type: smd.String,
									},
									{
										Name:     "identitySeqOpt",
										Optional: true,
										Ref:      "#/definitions/IdentitySeqOpt",
										Type:     smd.Object,
									},
									{
										Name: "generated",
										Type: smd.String,
									},
									{
										Name: "generatedStored",
										Type: smd.Boolean,
									},
									{
										Name: "comment",
										Type: smd.String,
									},
									{
										Name: "compression",
										Type: smd.String,
									},
									{
										Name: "storage",
										Type: smd.String,
									},
									{
										Name: "collation",
										Type: smd.String,
									},
								},
							},
							"IdentitySeqOpt": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "start",
										Type: smd.Integer,
									},
									{
										Name: "increment",
										Type: smd.Integer,
									},
									{
										Name: "min",
										Type: smd.Integer,
									},
									{
										Name: "max",
										Type: smd.Integer,
									},
									{
										Name: "cache",
										Type: smd.Integer,
									},
									{
										Name: "cycle",
										Type: smd.Boolean,
									},
								},
							},
						},
					},
					{
						Name:        "pk",
						Optional:    true,
						Description: `PK constraint (null name = remove)`,
						Type:        smd.Object,
						TypeName:    "PKInput",
						Properties: smd.PropertyList{
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name: "columns",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
						},
					},
					{
						Name:        "fks",
						Description: `full FK list replacement`,
						Type:        smd.Array,
						TypeName:    "[]FKInput",
						Items: map[string]string{
							"$ref": "#/definitions/FKInput",
						},
						Definitions: map[string]smd.Definition{
							"FKInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "toTable",
										Type: smd.String,
									},
									{
										Name: "onDelete",
										Type: smd.String,
									},
									{
										Name: "onUpdate",
										Type: smd.String,
									},
									{
										Name: "deferrable",
										Type: smd.Boolean,
									},
									{
										Name: "initially",
										Type: smd.String,
									},
									{
										Name: "columns",
										Type: smd.Array,
										Items: map[string]string{
											"$ref": "#/definitions/FKColInput",
										},
									},
								},
							},
							"FKColInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "references",
										Type: smd.String,
									},
								},
							},
						},
					},
					{
						Name:        "uniques",
						Description: `full UNIQUE list replacement`,
						Type:        smd.Array,
						TypeName:    "[]UniqueInput",
						Items: map[string]string{
							"$ref": "#/definitions/UniqueInput",
						},
						Definitions: map[string]smd.Definition{
							"UniqueInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "columns",
										Type: smd.Array,
										Items: map[string]string{
											"type": smd.String,
										},
									},
									{
										Name: "nullsDistinct",
										Type: smd.Boolean,
									},
								},
							},
						},
					},
					{
						Name:        "checks",
						Description: `full CHECK list replacement`,
						Type:        smd.Array,
						TypeName:    "[]CheckInput",
						Items: map[string]string{
							"$ref": "#/definitions/CheckInput",
						},
						Definitions: map[string]smd.Definition{
							"CheckInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "expression",
										Type: smd.String,
									},
								},
							},
						},
					},
					{
						Name:        "excludes",
						Description: `full EXCLUDE list replacement`,
						Type:        smd.Array,
						TypeName:    "[]ExcludeInput",
						Items: map[string]string{
							"$ref": "#/definitions/ExcludeInput",
						},
						Definitions: map[string]smd.Definition{
							"ExcludeInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "using",
										Type: smd.String,
									},
									{
										Name: "elements",
										Type: smd.Array,
										Items: map[string]string{
											"$ref": "#/definitions/ExcludeElementInput",
										},
									},
								},
							},
							"ExcludeElementInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "column",
										Type: smd.String,
									},
									{
										Name: "with",
										Type: smd.String,
									},
								},
							},
						},
					},
					{
						Name:        "indexes",
						Description: `full index list replacement`,
						Type:        smd.Array,
						TypeName:    "[]IndexInput",
						Items: map[string]string{
							"$ref": "#/definitions/IndexInput",
						},
						Definitions: map[string]smd.Definition{
							"IndexInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "table",
										Type: smd.String,
									},
									{
										Name: "unique",
										Type: smd.Boolean,
									},
									{
										Name: "nullsDistinct",
										Type: smd.Boolean,
									},
									{
										Name: "using",
										Type: smd.String,
									},
									{
										Name: "columns",
										Type: smd.Array,
										Items: map[string]string{
											"$ref": "#/definitions/IndexColInput",
										},
									},
									{
										Name: "expressions",
										Type: smd.Array,
										Items: map[string]string{
											"type": smd.String,
										},
									},
									{
										Name: "where",
										Type: smd.String,
									},
									{
										Name: "include",
										Type: smd.Array,
										Items: map[string]string{
											"type": smd.String,
										},
									},
								},
							},
							"IndexColInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "order",
										Type: smd.String,
									},
									{
										Name: "nulls",
										Type: smd.String,
									},
									{
										Name: "opclass",
										Type: smd.String,
									},
								},
							},
						},
					},
					{
						Name:     "partitionBy",
						Optional: true,
						Type:     smd.Object,
						TypeName: "PartitionByRPC",
						Properties: smd.PropertyList{
							{
								Name:        "type",
								Description: `range | list | hash`,
								Type:        smd.String,
							},
							{
								Name: "columns",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
						},
					},
					{
						Name:     "partitions",
						Type:     smd.Array,
						TypeName: "[]PartitionRPC",
						Items: map[string]string{
							"$ref": "#/definitions/PartitionRPC",
						},
						Definitions: map[string]smd.Definition{
							"PartitionRPC": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "bound",
										Type: smd.String,
									},
								},
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `TableDetail`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "TableDetail",
					Properties: smd.PropertyList{
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "schema",
							Type: smd.String,
						},
						{
							Name: "unlogged",
							Type: smd.Boolean,
						},
						{
							Name: "tablespace",
							Type: smd.String,
						},
						{
							Name: "comment",
							Type: smd.String,
						},
						{
							Name: "columns",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/ColumnDetail",
							},
						},
						{
							Name:     "pk",
							Optional: true,
							Ref:      "#/definitions/PKDetail",
							Type:     smd.Object,
						},
						{
							Name: "uniques",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/UniqueDetail",
							},
						},
						{
							Name: "checks",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/CheckDetail",
							},
						},
						{
							Name: "excludes",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/ExcludeDetail",
							},
						},
						{
							Name: "fks",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/FKDetail",
							},
						},
						{
							Name: "indexes",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/IndexDetail",
							},
						},
						{
							Name:     "partitionBy",
							Optional: true,
							Ref:      "#/definitions/PartitionByRPC",
							Type:     smd.Object,
						},
						{
							Name: "partitions",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/PartitionRPC",
							},
						},
						{
							Name: "ddl",
							Type: smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"ColumnDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "type",
									Type: smd.String,
								},
								{
									Name: "length",
									Type: smd.Integer,
								},
								{
									Name: "precision",
									Type: smd.Integer,
								},
								{
									Name: "scale",
									Type: smd.Integer,
								},
								{
									Name: "nullable",
									Type: smd.Boolean,
								},
								{
									Name: "default",
									Type: smd.String,
								},
								{
									Name: "pk",
									Type: smd.Boolean,
								},
								{
									Name: "fk",
									Type: smd.Boolean,
								},
								{
									Name: "identity",
									Type: smd.String,
								},
								{
									Name:     "identitySeqOpt",
									Optional: true,
									Ref:      "#/definitions/IdentitySeqOpt",
									Type:     smd.Object,
								},
								{
									Name: "generated",
									Type: smd.String,
								},
								{
									Name: "generatedStored",
									Type: smd.Boolean,
								},
								{
									Name: "comment",
									Type: smd.String,
								},
								{
									Name: "compression",
									Type: smd.String,
								},
								{
									Name: "storage",
									Type: smd.String,
								},
								{
									Name: "collation",
									Type: smd.String,
								},
							},
						},
						"IdentitySeqOpt": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "start",
									Type: smd.Integer,
								},
								{
									Name: "increment",
									Type: smd.Integer,
								},
								{
									Name: "min",
									Type: smd.Integer,
								},
								{
									Name: "max",
									Type: smd.Integer,
								},
								{
									Name: "cache",
									Type: smd.Integer,
								},
								{
									Name: "cycle",
									Type: smd.Boolean,
								},
							},
						},
						"PKDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
							},
						},
						"UniqueDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "nullsDistinct",
									Type: smd.Boolean,
								},
							},
						},
						"CheckDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "expression",
									Type: smd.String,
								},
							},
						},
						"ExcludeDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "using",
									Type: smd.String,
								},
								{
									Name: "elements",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/ExcludeElementDetail",
									},
								},
							},
						},
						"ExcludeElementDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "column",
									Type: smd.String,
								},
								{
									Name: "with",
									Type: smd.String,
								},
							},
						},
						"FKDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "toTable",
									Type: smd.String,
								},
								{
									Name: "onDelete",
									Type: smd.String,
								},
								{
									Name: "onUpdate",
									Type: smd.String,
								},
								{
									Name: "deferrable",
									Type: smd.Boolean,
								},
								{
									Name: "initially",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/FKColDetail",
									},
								},
							},
						},
						"FKColDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "references",
									Type: smd.String,
								},
							},
						},
						"IndexDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "unique",
									Type: smd.Boolean,
								},
								{
									Name: "nullsDistinct",
									Type: smd.Boolean,
								},
								{
									Name: "using",
									Type: smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/IndexColDetail",
									},
								},
								{
									Name: "expressions",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "where",
									Type: smd.String,
								},
								{
									Name: "include",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
							},
						},
						"IndexColDetail": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name:        "order",
									Description: `asc|desc`,
									Type:        smd.String,
								},
								{
									Name:        "nulls",
									Description: `first|last`,
									Type:        smd.String,
								},
								{
									Name: "opclass",
									Type: smd.String,
								},
							},
						},
						"PartitionByRPC": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:        "type",
									Description: `range | list | hash`,
									Type:        smd.String,
								},
								{
									Name: "columns",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
							},
						},
						"PartitionRPC": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "bound",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"PreviewDiff": {
				Description: `PreviewDiff returns ALTER SQL that would result from applying the given changes.
It does NOT modify the project — only computes the diff.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `qualified table name`,
						Type:        smd.String,
					},
					{
						Name:        "general",
						Optional:    true,
						Description: `table properties`,
						Type:        smd.Object,
						TypeName:    "GeneralInput",
						Properties: smd.PropertyList{
							{
								Name:     "name",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "comment",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "unlogged",
								Optional: true,
								Type:     smd.Boolean,
							},
							{
								Name:     "generate",
								Optional: true,
								Type:     smd.Boolean,
							},
						},
					},
					{
						Name:        "columns",
						Description: `full column list`,
						Type:        smd.Array,
						TypeName:    "[]ColumnInput",
						Items: map[string]string{
							"$ref": "#/definitions/ColumnInput",
						},
						Definitions: map[string]smd.Definition{
							"ColumnInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "type",
										Type: smd.String,
									},
									{
										Name: "length",
										Type: smd.Integer,
									},
									{
										Name: "precision",
										Type: smd.Integer,
									},
									{
										Name: "scale",
										Type: smd.Integer,
									},
									{
										Name: "nullable",
										Type: smd.Boolean,
									},
									{
										Name: "default",
										Type: smd.String,
									},
									{
										Name: "identity",
										Type: smd.String,
									},
									{
										Name:     "identitySeqOpt",
										Optional: true,
										Ref:      "#/definitions/IdentitySeqOpt",
										Type:     smd.Object,
									},
									{
										Name: "generated",
										Type: smd.String,
									},
									{
										Name: "generatedStored",
										Type: smd.Boolean,
									},
									{
										Name: "comment",
										Type: smd.String,
									},
									{
										Name: "compression",
										Type: smd.String,
									},
									{
										Name: "storage",
										Type: smd.String,
									},
									{
										Name: "collation",
										Type: smd.String,
									},
								},
							},
							"IdentitySeqOpt": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "start",
										Type: smd.Integer,
									},
									{
										Name: "increment",
										Type: smd.Integer,
									},
									{
										Name: "min",
										Type: smd.Integer,
									},
									{
										Name: "max",
										Type: smd.Integer,
									},
									{
										Name: "cache",
										Type: smd.Integer,
									},
									{
										Name: "cycle",
										Type: smd.Boolean,
									},
								},
							},
						},
					},
					{
						Name:        "pk",
						Optional:    true,
						Description: `PK constraint`,
						Type:        smd.Object,
						TypeName:    "PKInput",
						Properties: smd.PropertyList{
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name: "columns",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
						},
					},
					{
						Name:        "fks",
						Description: `full FK list`,
						Type:        smd.Array,
						TypeName:    "[]FKInput",
						Items: map[string]string{
							"$ref": "#/definitions/FKInput",
						},
						Definitions: map[string]smd.Definition{
							"FKInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "toTable",
										Type: smd.String,
									},
									{
										Name: "onDelete",
										Type: smd.String,
									},
									{
										Name: "onUpdate",
										Type: smd.String,
									},
									{
										Name: "deferrable",
										Type: smd.Boolean,
									},
									{
										Name: "initially",
										Type: smd.String,
									},
									{
										Name: "columns",
										Type: smd.Array,
										Items: map[string]string{
											"$ref": "#/definitions/FKColInput",
										},
									},
								},
							},
							"FKColInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "references",
										Type: smd.String,
									},
								},
							},
						},
					},
					{
						Name:        "uniques",
						Description: `full UNIQUE list`,
						Type:        smd.Array,
						TypeName:    "[]UniqueInput",
						Items: map[string]string{
							"$ref": "#/definitions/UniqueInput",
						},
						Definitions: map[string]smd.Definition{
							"UniqueInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "columns",
										Type: smd.Array,
										Items: map[string]string{
											"type": smd.String,
										},
									},
									{
										Name: "nullsDistinct",
										Type: smd.Boolean,
									},
								},
							},
						},
					},
					{
						Name:        "checks",
						Description: `full CHECK list`,
						Type:        smd.Array,
						TypeName:    "[]CheckInput",
						Items: map[string]string{
							"$ref": "#/definitions/CheckInput",
						},
						Definitions: map[string]smd.Definition{
							"CheckInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "expression",
										Type: smd.String,
									},
								},
							},
						},
					},
					{
						Name:        "excludes",
						Description: `full EXCLUDE list`,
						Type:        smd.Array,
						TypeName:    "[]ExcludeInput",
						Items: map[string]string{
							"$ref": "#/definitions/ExcludeInput",
						},
						Definitions: map[string]smd.Definition{
							"ExcludeInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "using",
										Type: smd.String,
									},
									{
										Name: "elements",
										Type: smd.Array,
										Items: map[string]string{
											"$ref": "#/definitions/ExcludeElementInput",
										},
									},
								},
							},
							"ExcludeElementInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "column",
										Type: smd.String,
									},
									{
										Name: "with",
										Type: smd.String,
									},
								},
							},
						},
					},
					{
						Name:        "indexes",
						Description: `full index list`,
						Type:        smd.Array,
						TypeName:    "[]IndexInput",
						Items: map[string]string{
							"$ref": "#/definitions/IndexInput",
						},
						Definitions: map[string]smd.Definition{
							"IndexInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "table",
										Type: smd.String,
									},
									{
										Name: "unique",
										Type: smd.Boolean,
									},
									{
										Name: "nullsDistinct",
										Type: smd.Boolean,
									},
									{
										Name: "using",
										Type: smd.String,
									},
									{
										Name: "columns",
										Type: smd.Array,
										Items: map[string]string{
											"$ref": "#/definitions/IndexColInput",
										},
									},
									{
										Name: "expressions",
										Type: smd.Array,
										Items: map[string]string{
											"type": smd.String,
										},
									},
									{
										Name: "where",
										Type: smd.String,
									},
									{
										Name: "include",
										Type: smd.Array,
										Items: map[string]string{
											"type": smd.String,
										},
									},
								},
							},
							"IndexColInput": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "name",
										Type: smd.String,
									},
									{
										Name: "order",
										Type: smd.String,
									},
									{
										Name: "nulls",
										Type: smd.String,
									},
									{
										Name: "opclass",
										Type: smd.String,
									},
								},
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]DiffChange`,
					Type:        smd.Array,
					TypeName:    "[]DiffChange",
					Items: map[string]string{
						"$ref": "#/definitions/DiffChange",
					},
					Definitions: map[string]smd.Definition{
						"DiffChange": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:        "object",
									Description: `table, column, index, fk, pk, unique, check, enum`,
									Type:        smd.String,
								},
								{
									Name:        "action",
									Description: `add, drop, alter`,
									Type:        smd.String,
								},
								{
									Name:        "table",
									Description: `parent table (for column/constraint changes)`,
									Type:        smd.String,
								},
								{
									Name:        "name",
									Description: `object name`,
									Type:        smd.String,
								},
								{
									Name:        "sql",
									Description: `generated ALTER/CREATE/DROP`,
									Type:        smd.String,
								},
								{
									Name:        "hazards",
									Description: `warnings`,
									Type:        smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/DiffHazard",
									},
								},
							},
						},
						"DiffHazard": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:        "level",
									Description: `dangerous, warning, info`,
									Type:        smd.String,
								},
								{
									Name:        "code",
									Description: `DELETES_DATA, TABLE_REWRITE, etc.`,
									Type:        smd.String,
								},
								{
									Name: "message",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"DiffUnsaved": {
				Description: `DiffUnsaved returns ALTER SQL for all unsaved changes (saved snapshot vs current state).`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `DiffUnsavedResult`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "DiffUnsavedResult",
					Properties: smd.PropertyList{
						{
							Name: "changes",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/DiffChange",
							},
						},
						{
							Name:        "sql",
							Description: `full ALTER script`,
							Type:        smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"DiffChange": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:        "object",
									Description: `table, column, index, fk, pk, unique, check, enum`,
									Type:        smd.String,
								},
								{
									Name:        "action",
									Description: `add, drop, alter`,
									Type:        smd.String,
								},
								{
									Name:        "table",
									Description: `parent table (for column/constraint changes)`,
									Type:        smd.String,
								},
								{
									Name:        "name",
									Description: `object name`,
									Type:        smd.String,
								},
								{
									Name:        "sql",
									Description: `generated ALTER/CREATE/DROP`,
									Type:        smd.String,
								},
								{
									Name:        "hazards",
									Description: `warnings`,
									Type:        smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/DiffHazard",
									},
								},
							},
						},
						"DiffHazard": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:        "level",
									Description: `dangerous, warning, info`,
									Type:        smd.String,
								},
								{
									Name:        "code",
									Description: `DELETES_DATA, TABLE_REWRITE, etc.`,
									Type:        smd.String,
								},
								{
									Name: "message",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
			"FixLintIssues": {
				Description: `FixLintIssues applies auto-fixes for selected lint issues.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "issues",
						Description: `selected issues (code + path pairs)`,
						Type:        smd.Array,
						TypeName:    "[]LintFixRequest",
						Items: map[string]string{
							"$ref": "#/definitions/LintFixRequest",
						},
						Definitions: map[string]smd.Definition{
							"LintFixRequest": {
								Type: "object",
								Properties: smd.PropertyList{
									{
										Name: "code",
										Type: smd.String,
									},
									{
										Name: "path",
										Type: smd.String,
									},
								},
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `FixLintResult`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "FixLintResult",
					Properties: smd.PropertyList{
						{
							Name: "fixed",
							Type: smd.Integer,
						},
						{
							Name: "issues",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/LintIssue",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"LintIssue": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "severity",
									Type: smd.String,
								},
								{
									Name: "code",
									Type: smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "path",
									Type: smd.String,
								},
								{
									Name: "message",
									Type: smd.String,
								},
								{
									Name: "fixable",
									Type: smd.Boolean,
								},
							},
						},
					},
				},
			},
			"IgnoreLintRules": {
				Description: `IgnoreLintRules adds rules to project or table ignore list.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "rules",
						Description: `rule codes to ignore`,
						Type:        smd.Array,
						TypeName:    "[]",
						Items: map[string]string{
							"type": smd.String,
						},
					},
					{
						Name:        "table",
						Optional:    true,
						Description: `optional qualified table name (null = project level)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]LintIssue`,
					Type:        smd.Array,
					TypeName:    "[]LintIssue",
					Items: map[string]string{
						"$ref": "#/definitions/LintIssue",
					},
					Definitions: map[string]smd.Definition{
						"LintIssue": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "severity",
									Type: smd.String,
								},
								{
									Name: "code",
									Type: smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "path",
									Type: smd.String,
								},
								{
									Name: "message",
									Type: smd.String,
								},
								{
									Name: "fixable",
									Type: smd.Boolean,
								},
							},
						},
					},
				},
			},
			"GetIgnoredRules": {
				Description: `GetIgnoredRules returns all ignored lint rules from project and table settings.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]IgnoredRule`,
					Type:        smd.Array,
					TypeName:    "[]IgnoredRule",
					Items: map[string]string{
						"$ref": "#/definitions/IgnoredRule",
					},
					Definitions: map[string]smd.Definition{
						"IgnoredRule": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "code",
									Type: smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name:        "scope",
									Description: `"project" or table name`,
									Type:        smd.String,
								},
							},
						},
					},
				},
			},
			"UnignoreLintRules": {
				Description: `UnignoreLintRules removes rules from project or table ignore list.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "rules",
						Description: `codes to unignore`,
						Type:        smd.Array,
						TypeName:    "[]",
						Items: map[string]string{
							"type": smd.String,
						},
					},
					{
						Name:        "table",
						Optional:    true,
						Description: `optional table name (null = project level)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"CreateTable": {
				Description: `CreateTable creates a new empty table in the specified schema.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "schemaName",
						Description: `schema name`,
						Type:        smd.String,
					},
					{
						Name:        "tableName",
						Description: `table name`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"DeleteTable": {
				Description: `DeleteTable removes a table and its indexes from the project.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `qualified table name`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"CreateSchema": {
				Description: `CreateSchema adds a new empty schema to the project.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `schema name`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"DeleteSchema": {
				Description: `DeleteSchema removes an empty schema from the project.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `schema name`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"MoveTable": {
				Description: `MoveTable transfers a table from its current schema to another.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `qualified table name`,
						Type:        smd.String,
					},
					{
						Name:        "toSchema",
						Description: `destination schema name`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"GetProjectSettings": {
				Description: `GetProjectSettings returns editable project settings.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `ProjectSettings`,
					Type:        smd.Object,
					TypeName:    "ProjectSettings",
					Properties: smd.PropertyList{
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name: "pgVersion",
							Type: smd.String,
						},
						{
							Name: "defaultSchema",
							Type: smd.String,
						},
						{
							Name:        "namingConvention",
							Description: `Naming`,
							Type:        smd.String,
						},
						{
							Name: "namingTables",
							Type: smd.String,
						},
						{
							Name:        "defaultNullable",
							Description: `Defaults`,
							Type:        smd.String,
						},
						{
							Name: "defaultOnDelete",
							Type: smd.String,
						},
						{
							Name: "defaultOnUpdate",
							Type: smd.String,
						},
						{
							Name:        "lintIgnoreRules",
							Description: `Lint`,
							Type:        smd.String,
						},
					},
				},
			},
			"UpdateProjectSettings": {
				Description: `UpdateProjectSettings saves project-level settings.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "settings",
						Description: `project settings`,
						Type:        smd.Object,
						TypeName:    "ProjectSettings",
						Properties: smd.PropertyList{
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name: "description",
								Type: smd.String,
							},
							{
								Name: "pgVersion",
								Type: smd.String,
							},
							{
								Name: "defaultSchema",
								Type: smd.String,
							},
							{
								Name:        "namingConvention",
								Description: `Naming`,
								Type:        smd.String,
							},
							{
								Name: "namingTables",
								Type: smd.String,
							},
							{
								Name:        "defaultNullable",
								Description: `Defaults`,
								Type:        smd.String,
							},
							{
								Name: "defaultOnDelete",
								Type: smd.String,
							},
							{
								Name: "defaultOnUpdate",
								Type: smd.String,
							},
							{
								Name:        "lintIgnoreRules",
								Description: `Lint`,
								Type:        smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
			},
			"LintTable": {
				Description: `LintTable validates a single table and returns all lint issues.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `table name`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]LintIssue`,
					Type:        smd.Array,
					TypeName:    "[]LintIssue",
					Items: map[string]string{
						"$ref": "#/definitions/LintIssue",
					},
					Definitions: map[string]smd.Definition{
						"LintIssue": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "severity",
									Type: smd.String,
								},
								{
									Name: "code",
									Type: smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "path",
									Type: smd.String,
								},
								{
									Name: "message",
									Type: smd.String,
								},
								{
									Name: "fixable",
									Type: smd.Boolean,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "Not Found",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s ProjectService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.ProjectService.GetInfo:
		resp.Set(s.GetInfo())

	case RPC.ProjectService.GetSchema:
		resp.Set(s.GetSchema())

	case RPC.ProjectService.GetDDL:
		resp.Set(s.GetDDL())

	case RPC.ProjectService.Lint:
		resp.Set(s.Lint())

	case RPC.ProjectService.ListObjects:
		resp.Set(s.ListObjects())

	case RPC.ProjectService.GetTable:
		var args = struct {
			Name string `json:"name"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetTable(args.Name))

	case RPC.ProjectService.SaveProject:
		resp.Set(s.SaveProject())

	case RPC.ProjectService.SaveLayout:
		var args = struct {
			Positions []LayoutPosition `json:"positions"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"positions"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.SaveLayout(args.Positions))

	case RPC.ProjectService.IsDirty:
		resp.Set(s.IsDirty())

	case RPC.ProjectService.GetAutoSave:
		resp.Set(s.GetAutoSave())

	case RPC.ProjectService.SetAutoSave:
		var args = struct {
			Enabled bool `json:"enabled"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"enabled"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.SetAutoSave(args.Enabled))

	case RPC.ProjectService.ListTypes:
		resp.Set(s.ListTypes())

	case RPC.ProjectService.UpdateTable:
		var args = struct {
			Name        string          `json:"name"`
			General     *GeneralInput   `json:"general"`
			Columns     []ColumnInput   `json:"columns"`
			Pk          *PKInput        `json:"pk"`
			Fks         []FKInput       `json:"fks"`
			Uniques     []UniqueInput   `json:"uniques"`
			Checks      []CheckInput    `json:"checks"`
			Excludes    []ExcludeInput  `json:"excludes"`
			Indexes     []IndexInput    `json:"indexes"`
			PartitionBy *PartitionByRPC `json:"partitionBy"`
			Partitions  []PartitionRPC  `json:"partitions"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name", "general", "columns", "pk", "fks", "uniques", "checks", "excludes", "indexes", "partitionBy", "partitions"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UpdateTable(args.Name, args.General, args.Columns, args.Pk, args.Fks, args.Uniques, args.Checks, args.Excludes, args.Indexes, args.PartitionBy, args.Partitions))

	case RPC.ProjectService.PreviewDiff:
		var args = struct {
			Name     string         `json:"name"`
			General  *GeneralInput  `json:"general"`
			Columns  []ColumnInput  `json:"columns"`
			Pk       *PKInput       `json:"pk"`
			Fks      []FKInput      `json:"fks"`
			Uniques  []UniqueInput  `json:"uniques"`
			Checks   []CheckInput   `json:"checks"`
			Excludes []ExcludeInput `json:"excludes"`
			Indexes  []IndexInput   `json:"indexes"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name", "general", "columns", "pk", "fks", "uniques", "checks", "excludes", "indexes"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.PreviewDiff(args.Name, args.General, args.Columns, args.Pk, args.Fks, args.Uniques, args.Checks, args.Excludes, args.Indexes))

	case RPC.ProjectService.DiffUnsaved:
		resp.Set(s.DiffUnsaved())

	case RPC.ProjectService.FixLintIssues:
		var args = struct {
			Issues []LintFixRequest `json:"issues"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"issues"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.FixLintIssues(args.Issues))

	case RPC.ProjectService.IgnoreLintRules:
		var args = struct {
			Rules []string `json:"rules"`
			Table *string  `json:"table"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"rules", "table"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.IgnoreLintRules(args.Rules, args.Table))

	case RPC.ProjectService.GetIgnoredRules:
		resp.Set(s.GetIgnoredRules())

	case RPC.ProjectService.UnignoreLintRules:
		var args = struct {
			Rules []string `json:"rules"`
			Table *string  `json:"table"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"rules", "table"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UnignoreLintRules(args.Rules, args.Table))

	case RPC.ProjectService.CreateTable:
		var args = struct {
			SchemaName string `json:"schemaName"`
			TableName  string `json:"tableName"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"schemaName", "tableName"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.CreateTable(args.SchemaName, args.TableName))

	case RPC.ProjectService.DeleteTable:
		var args = struct {
			Name string `json:"name"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.DeleteTable(args.Name))

	case RPC.ProjectService.CreateSchema:
		var args = struct {
			Name string `json:"name"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.CreateSchema(args.Name))

	case RPC.ProjectService.DeleteSchema:
		var args = struct {
			Name string `json:"name"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.DeleteSchema(args.Name))

	case RPC.ProjectService.MoveTable:
		var args = struct {
			Name     string `json:"name"`
			ToSchema string `json:"toSchema"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name", "toSchema"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.MoveTable(args.Name, args.ToSchema))

	case RPC.ProjectService.GetProjectSettings:
		resp.Set(s.GetProjectSettings())

	case RPC.ProjectService.UpdateProjectSettings:
		var args = struct {
			Settings ProjectSettings `json:"settings"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"settings"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.UpdateProjectSettings(args.Settings))

	case RPC.ProjectService.LintTable:
		var args = struct {
			Name string `json:"name"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.LintTable(args.Name))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
