package pgd

import (
	"bytes"
	"encoding/xml"
	"os"
	"os/exec"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateDDL_SimpleTable(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "statuses",
				Columns: []Column{
					{Name: "statusId", Type: "integer", Nullable: "false", Identity: &Identity{Generated: "by-default"}},
					{Name: "title", Type: "varchar", Length: 255, Nullable: "false"},
					{Name: "alias", Type: "varchar", Length: 64, Nullable: "false"},
				},
				PK: &PrimaryKey{Name: "pk_statuses", Columns: []ColRef{{Name: "statusId"}}},
				Uniques: []Unique{{
					Name:    "statuses_alias_key",
					Columns: []ColRef{{Name: "alias"}},
				}},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `CREATE TABLE "statuses"`)
	assert.Contains(t, ddl, `"statusId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY`)
	assert.Contains(t, ddl, `"title" varchar(255) NOT NULL`)
	assert.Contains(t, ddl, `"alias" varchar(64) NOT NULL`)
	assert.Contains(t, ddl, `PRIMARY KEY("statusId")`)
	assert.Contains(t, ddl, `CONSTRAINT "statuses_alias_key" UNIQUE("alias")`)
}

func TestGenerateDDL_Serial(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "legacy",
				Columns: []Column{
					{Name: "id", Type: "serial", Nullable: "false"},
					{Name: "bigId", Type: "bigserial", Nullable: "false"},
				},
				PK: &PrimaryKey{Name: "pk_legacy", Columns: []ColRef{{Name: "id"}}},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `"id" SERIAL NOT NULL`)
	assert.Contains(t, ddl, `"bigId" BIGSERIAL NOT NULL`)
	assert.NotContains(t, ddl, "IDENTITY")
}

func TestGenerateDDL_Identity(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "modern",
				Columns: []Column{
					{Name: "id", Type: "integer", Nullable: "false", Identity: &Identity{Generated: "always"}},
				},
				PK: &PrimaryKey{Name: "pk_modern", Columns: []ColRef{{Name: "id"}}},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `"id" integer NOT NULL GENERATED ALWAYS AS IDENTITY`)
	assert.NotContains(t, ddl, "SERIAL")
}

func TestGenerateDDL_ColumnTypes(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "types_test",
				Columns: []Column{
					{Name: "a", Type: "integer", Nullable: "false"},
					{Name: "b", Type: "varchar", Length: 100},
					{Name: "c", Type: "numeric", Precision: 12, Scale: 2, Nullable: "false"},
					{Name: "d", Type: "boolean", Default: "false"},
					{Name: "e", Type: "timestamptz", Nullable: "false", Default: "now()"},
					{Name: "f", Type: "jsonb"},
					{Name: "g", Type: "text[]"},
					{Name: "h", Type: "integer[]"},
					{Name: "i", Type: "point"},
				},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `"a" integer NOT NULL`)
	assert.Contains(t, ddl, `"b" varchar(100)`)
	assert.Contains(t, ddl, `"c" numeric(12,2) NOT NULL`)
	assert.Contains(t, ddl, `"d" boolean DEFAULT false`)
	assert.Contains(t, ddl, `"e" timestamptz NOT NULL DEFAULT now()`)
	assert.Contains(t, ddl, `"f" jsonb`)
	assert.Contains(t, ddl, `"g" text[]`)
	assert.Contains(t, ddl, `"h" integer[]`)
	assert.Contains(t, ddl, `"i" point`)
}

func TestGenerateDDL_CheckConstraint(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "orders",
				Columns: []Column{
					{Name: "id", Type: "integer", Nullable: "false"},
					{Name: "amount", Type: "numeric", Precision: 12, Scale: 2, Nullable: "false"},
				},
				PK: &PrimaryKey{Name: "pk_orders", Columns: []ColRef{{Name: "id"}}},
				Checks: []Check{{
					Name:       "amount_positive",
					Expression: "amount > 0",
				}},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `CONSTRAINT "amount_positive" CHECK(amount > 0)`)
}

func TestGenerateDDL_FK(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{
				{
					Name: "statuses",
					Columns: []Column{
						{Name: "statusId", Type: "integer", Nullable: "false"},
					},
					PK: &PrimaryKey{Name: "pk_statuses", Columns: []ColRef{{Name: "statusId"}}},
				},
				{
					Name: "users",
					Columns: []Column{
						{Name: "userId", Type: "integer", Nullable: "false"},
						{Name: "statusId", Type: "integer", Nullable: "false"},
					},
					PK: &PrimaryKey{Name: "pk_users", Columns: []ColRef{{Name: "userId"}}},
					FKs: []ForeignKey{{
						Name:     "fk_users_statuses",
						ToTable:  "statuses",
						OnDelete: "restrict",
						OnUpdate: "restrict",
						Columns:  []FKCol{{Name: "statusId", References: "statusId"}},
					}},
				},
			},
		}},
	}

	ddl := GenerateDDL(p)

	// FK must be in ALTER TABLE, not in CREATE TABLE
	lines := strings.Split(ddl, "\n")
	var createUsers, alterUsers bool
	for _, line := range lines {
		if strings.Contains(line, `CREATE TABLE "users"`) {
			createUsers = true
		}
		if strings.Contains(line, `ALTER TABLE "users" ADD CONSTRAINT`) && strings.Contains(line, "FOREIGN KEY") {
			alterUsers = true
		}
	}
	assert.True(t, createUsers, "should have CREATE TABLE users")
	assert.True(t, alterUsers, "should have ALTER TABLE users ADD FK")

	// FK should NOT appear inside CREATE TABLE
	inCreate := false
	for _, line := range lines {
		if strings.Contains(line, `CREATE TABLE "users"`) {
			inCreate = true
		}
		if inCreate && strings.Contains(line, ");") {
			inCreate = false
		}
		if inCreate {
			assert.NotContains(t, line, "FOREIGN KEY", "FK should not be inline in CREATE TABLE")
			assert.NotContains(t, line, "REFERENCES", "REFERENCES should not be inline in CREATE TABLE")
		}
	}

	assert.Contains(t, ddl, `REFERENCES "statuses"("statusId")`)
	assert.Contains(t, ddl, "ON DELETE RESTRICT")
	assert.Contains(t, ddl, "NOT DEFERRABLE")
}

func TestGenerateDDL_Index(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "users",
				Columns: []Column{
					{Name: "email", Type: "text"},
				},
			}},
			Indexes: []Index{
				{Name: "idx_users_email", Table: "users", Unique: "true", Columns: []ColRef{{Name: "email"}}},
				{Name: "idx_users_data", Table: "users", Using: "gin", Expressions: []Expression{{Value: `"data" jsonb_path_ops`}}},
				{Name: "idx_users_active", Table: "users", Columns: []ColRef{{Name: "email"}}, Where: &WhereClause{Value: `"active" = true`}},
				{Name: "idx_users_created", Table: "users", Columns: []ColRef{{Name: "email", Order: "desc", Nulls: "last"}}},
			},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `CREATE UNIQUE INDEX "idx_users_email"`)
	assert.Contains(t, ddl, `USING GIN`)
	assert.Contains(t, ddl, `"data" jsonb_path_ops`)
	assert.Contains(t, ddl, `WHERE "active" = true`)
	assert.Contains(t, ddl, `DESC NULLS LAST`)
}

func TestGenerateDDL_CompositePK(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "tags",
				Columns: []Column{
					{Name: "objectId", Type: "integer", Nullable: "false"},
					{Name: "tagId", Type: "integer", Nullable: "false"},
				},
				PK: &PrimaryKey{Name: "pk_tags", Columns: []ColRef{{Name: "objectId"}, {Name: "tagId"}}},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `PRIMARY KEY("objectId", "tagId")`)
}

func TestGenerateDDL_Golden(t *testing.T) {
	tests := []struct {
		name    string
		pgd     string
		golden  string
		tables  int
		fks     int
		indexes int
	}{
		{"chinook", "../format/sql/testdata/chinook.pgd", "../format/sql/testdata/chinook_generated.sql", 11, 11, 11},
		{"northwind", "../format/sql/testdata/northwind.pgd", "../format/sql/testdata/northwind_generated.sql", 14, 13, 0},
		{"pagila", "../format/sql/testdata/pagila.pgd", "../format/sql/testdata/pagila_generated.sql", 22, 18, 16},
		{"airlines", "../format/sql/testdata/airlines.pgd", "../format/sql/testdata/airlines_generated.sql", 8, 8, 0},
		{"adventureworks", "../format/sql/testdata/adventureworks.pgd", "../format/sql/testdata/adventureworks_generated.sql", 68, 89, 2},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := os.ReadFile(tt.pgd)
			require.NoError(t, err)

			var p Project
			require.NoError(t, xml.Unmarshal(data, &p))

			ddl := GenerateDDL(&p)

			// golden file comparison
			want, err := os.ReadFile(tt.golden)
			require.NoError(t, err)
			assert.Equal(t, string(want), ddl, "DDL mismatch with golden file %s", tt.golden)

			// object counts
			assert.Equal(t, tt.tables, strings.Count(ddl, "CREATE TABLE "), "table count")
			assert.Equal(t, tt.indexes, strings.Count(ddl, "CREATE INDEX ")+strings.Count(ddl, "CREATE UNIQUE INDEX "), "index count")
			assert.Equal(t, tt.fks, strings.Count(ddl, "ALTER TABLE"), "FK count")

			// structure: CREATE TABLE before CREATE INDEX before ALTER TABLE
			createTablePos := strings.Index(ddl, "CREATE TABLE")
			createIndexPos := strings.Index(ddl, "CREATE INDEX")
			alterPos := strings.Index(ddl, "ALTER TABLE")

			if createIndexPos > 0 {
				assert.Less(t, createTablePos, createIndexPos, "CREATE TABLE should come before CREATE INDEX")
			}
			if alterPos > 0 {
				assert.Less(t, createTablePos, alterPos, "CREATE TABLE should come before ALTER TABLE")
			}
			if createIndexPos > 0 && alterPos > 0 {
				assert.Less(t, createIndexPos, alterPos, "CREATE INDEX should come before ALTER TABLE")
			}
		})
	}
}

func TestGenerateDDL_Pagila_Content(t *testing.T) {
	data, err := os.ReadFile("../format/sql/testdata/pagila.pgd")
	require.NoError(t, err)

	var p Project
	require.NoError(t, xml.Unmarshal(data, &p))

	ddl := GenerateDDL(&p)

	// enum type
	assert.Contains(t, ddl, "CREATE TYPE")

	// domains
	assert.Contains(t, ddl, "CREATE DOMAIN")

	// partitions
	assert.Contains(t, ddl, "PARTITION BY RANGE")
	assert.Contains(t, ddl, "PARTITION OF")

	// aggregate
	assert.Contains(t, ddl, "CREATE AGGREGATE")

	// triggers
	assert.Contains(t, ddl, "CREATE TRIGGER")

	// FK syntax
	assert.Contains(t, ddl, "NOT DEFERRABLE")
}

func TestGenerateDDL_PartitionByRange(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "payment",
				Columns: []Column{
					{Name: "payment_id", Type: "integer", Nullable: "false"},
					{Name: "amount", Type: "numeric", Precision: 5, Scale: 2, Nullable: "false"},
					{Name: "payment_date", Type: "timestamptz", Nullable: "false"},
				},
				PK: &PrimaryKey{Name: "pk_payment", Columns: []ColRef{{Name: "payment_id"}, {Name: "payment_date"}}},
				PartitionBy: &PartitionBy{
					Type:    "range",
					Columns: []ColRef{{Name: "payment_date"}},
				},
				Partitions: []Partition{
					{Name: "payment_p2024_01", Bound: "FOR VALUES FROM ('2024-01-01') TO ('2024-02-01')"},
					{Name: "payment_p2024_02", Bound: "FOR VALUES FROM ('2024-02-01') TO ('2024-03-01')"},
					{Name: "payment_default", Bound: "DEFAULT"},
				},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	// Parent table should have PARTITION BY
	assert.Contains(t, ddl, `PARTITION BY RANGE ("payment_date")`)

	// Children should be CREATE TABLE ... PARTITION OF
	assert.Contains(t, ddl, `CREATE TABLE "payment_p2024_01" PARTITION OF "payment"`)
	assert.Contains(t, ddl, `FOR VALUES FROM ('2024-01-01') TO ('2024-02-01')`)
	assert.Contains(t, ddl, `CREATE TABLE "payment_p2024_02" PARTITION OF "payment"`)
	assert.Contains(t, ddl, `CREATE TABLE "payment_default" PARTITION OF "payment"`)
	assert.Contains(t, ddl, "DEFAULT")

	// Children should NOT be separate CREATE TABLE with columns
	assert.Equal(t, 1, strings.Count(ddl, `"payment_id" integer NOT NULL`), "columns should appear only once (in parent)")
}

func TestGenerateDDL_PartitionMultiLevel(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "measurement",
				Columns: []Column{
					{Name: "logdate", Type: "date", Nullable: "false"},
					{Name: "city", Type: "text", Nullable: "false"},
					{Name: "peaktemp", Type: "integer"},
				},
				PartitionBy: &PartitionBy{
					Type:    "range",
					Columns: []ColRef{{Name: "logdate"}},
				},
				Partitions: []Partition{
					{
						Name:  "measurement_y2024",
						Bound: "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')",
						PartitionBy: &PartitionBy{
							Type:    "list",
							Columns: []ColRef{{Name: "city"}},
						},
						Partitions: []Partition{
							{Name: "measurement_y2024_ny", Bound: "FOR VALUES IN ('New York')"},
							{Name: "measurement_y2024_la", Bound: "FOR VALUES IN ('Los Angeles')"},
						},
					},
				},
			}},
		}},
	}

	ddl := GenerateDDL(p)

	assert.Contains(t, ddl, `PARTITION BY RANGE ("logdate")`)
	assert.Contains(t, ddl, `CREATE TABLE "measurement_y2024" PARTITION OF "measurement"`)
	assert.Contains(t, ddl, `PARTITION BY LIST ("city")`)
	assert.Contains(t, ddl, `CREATE TABLE "measurement_y2024_ny" PARTITION OF "measurement_y2024"`)
	assert.Contains(t, ddl, `FOR VALUES IN ('New York')`)
	assert.Contains(t, ddl, `CREATE TABLE "measurement_y2024_la" PARTITION OF "measurement_y2024"`)
}

func TestMigratePartitions(t *testing.T) {
	// Variant A: separate tables with PartitionOf
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{
				{
					Name: "payment",
					Columns: []Column{
						{Name: "payment_id", Type: "integer"},
						{Name: "payment_date", Type: "timestamptz"},
					},
					PartitionBy: &PartitionBy{Type: "range", Columns: []ColRef{{Name: "payment_date"}}},
				},
				{
					Name:           "payment_p2024_01",
					PartitionOf:    "payment",
					PartitionBound: &PartitionBound{Value: "FOR VALUES FROM ('2024-01-01') TO ('2024-02-01')"},
					Columns: []Column{
						{Name: "payment_id", Type: "integer"},
						{Name: "payment_date", Type: "timestamptz"},
					},
				},
				{
					Name:           "payment_p2024_02",
					PartitionOf:    "payment",
					PartitionBound: &PartitionBound{Value: "FOR VALUES FROM ('2024-02-01') TO ('2024-03-01')"},
					Columns: []Column{
						{Name: "payment_id", Type: "integer"},
						{Name: "payment_date", Type: "timestamptz"},
					},
				},
			},
		}},
	}

	MigratePartitions(p)

	// Should have only 1 table (parent)
	assert.Len(t, p.Schemas[0].Tables, 1)
	parent := p.Schemas[0].Tables[0]
	assert.Equal(t, "payment", parent.Name)
	assert.Len(t, parent.Partitions, 2)
	assert.Equal(t, "payment_p2024_01", parent.Partitions[0].Name)
	assert.Equal(t, "FOR VALUES FROM ('2024-01-01') TO ('2024-02-01')", parent.Partitions[0].Bound)
	assert.Equal(t, "payment_p2024_02", parent.Partitions[1].Name)
}

func TestGenerateDDL_VariantA_SkipPartitionChildren(t *testing.T) {
	// Variant A tables with PartitionOf should be skipped in DDL
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{
				{
					Name:        "payment",
					Columns:     []Column{{Name: "id", Type: "integer"}},
					PartitionBy: &PartitionBy{Type: "range", Columns: []ColRef{{Name: "id"}}},
					Partitions: []Partition{
						{Name: "payment_p1", Bound: "FOR VALUES FROM (1) TO (100)"},
					},
				},
				{
					Name:        "orphan_child",
					PartitionOf: "payment",
					Columns:     []Column{{Name: "id", Type: "integer"}},
				},
			},
		}},
	}

	ddl := GenerateDDL(p)

	// orphan_child (Variant A) should not appear as CREATE TABLE
	assert.NotContains(t, ddl, `CREATE TABLE "orphan_child" (`)
	// But Variant B child should appear
	assert.Contains(t, ddl, `CREATE TABLE "payment_p1" PARTITION OF "payment"`)
}

func TestGenerateDDL_AdventureWorks_Content(t *testing.T) {
	data, err := os.ReadFile("../format/sql/testdata/adventureworks.pgd")
	require.NoError(t, err)

	var p Project
	require.NoError(t, xml.Unmarshal(data, &p))

	ddl := GenerateDDL(&p)

	// multi-schema: CREATE SCHEMA
	assert.Contains(t, ddl, "CREATE SCHEMA IF NOT EXISTS")

	// domains with mixed-case should be quoted
	assert.Contains(t, ddl, `"Flag"`)
	assert.Contains(t, ddl, "CREATE DOMAIN")

	// views
	assert.Contains(t, ddl, "CREATE VIEW")

	// comments
	assert.Contains(t, ddl, "COMMENT ON TABLE")
	assert.Contains(t, ddl, "COMMENT ON COLUMN")
}

// --- WriteTable / WriteIndex / WriteFK / GenerateTableDDL ---

func TestWriteTable(t *testing.T) {
	tbl := &Table{
		Name: "users",
		Columns: []Column{
			{Name: "id", Type: "integer", Nullable: "false"},
			{Name: "name", Type: "varchar", Length: 100},
		},
		PK: &PrimaryKey{Name: "pk_users", Columns: []ColRef{{Name: "id"}}},
	}
	var buf bytes.Buffer
	err := WriteTable(&buf, "", tbl)
	require.NoError(t, err)
	sql := buf.String()
	assert.Contains(t, sql, `CREATE TABLE "users"`)
	assert.Contains(t, sql, `"id" integer NOT NULL`)
	assert.Contains(t, sql, `varchar(100)`)
	assert.Contains(t, sql, `PRIMARY KEY`)
}

func TestWriteIndex(t *testing.T) {
	idx := &Index{
		Name:   "idx_users_name",
		Table:  "users",
		Unique: "true",
		Columns: []ColRef{
			{Name: "name", Order: "asc"},
		},
		Where: &WhereClause{Value: `"active" = true`},
	}
	var buf bytes.Buffer
	err := WriteIndex(&buf, "", idx)
	require.NoError(t, err)
	sql := buf.String()
	assert.Contains(t, sql, "CREATE UNIQUE INDEX")
	assert.Contains(t, sql, `"idx_users_name"`)
	assert.Contains(t, sql, "WHERE")
}

func TestWriteFK(t *testing.T) {
	fk := &ForeignKey{
		Name:     "fk_orders_user",
		ToTable:  "users",
		OnDelete: "cascade",
		OnUpdate: "no action",
		Columns:  []FKCol{{Name: "user_id", References: "id"}},
	}
	var buf bytes.Buffer
	err := WriteFK(&buf, "", "orders", fk)
	require.NoError(t, err)
	sql := buf.String()
	assert.Contains(t, sql, "ALTER TABLE")
	assert.Contains(t, sql, `REFERENCES "users"`)
	assert.Contains(t, sql, "ON DELETE CASCADE")
}

func TestGenerateTableDDL(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "items",
				Columns: []Column{
					{Name: "id", Type: "serial", Nullable: "false"},
					{Name: "title", Type: "text"},
				},
				PK: &PrimaryKey{Name: "pk_items", Columns: []ColRef{{Name: "id"}}},
			}},
			Indexes: []Index{{
				Name: "idx_items_title", Table: "items",
				Columns: []ColRef{{Name: "title"}},
			}},
		}},
	}
	ddl := GenerateTableDDL(p, "items")
	assert.Contains(t, ddl, `CREATE TABLE "items"`)
	assert.Contains(t, ddl, "SERIAL NOT NULL")
	assert.Contains(t, ddl, `CREATE INDEX "idx_items_title"`)
}

// --- Composite / Range types ---

func TestGenerateDDL_Composite(t *testing.T) {
	p := &Project{
		Types: &Types{
			Composites: []Composite{
				{Name: "address", Schema: "public", Fields: []CompositeField{
					{Name: "street", Type: "text"},
					{Name: "city", Type: "varchar", Length: 100},
				}},
			},
		},
		Schemas: []Schema{{Name: "public"}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, "CREATE TYPE")
	assert.Contains(t, ddl, `"address"`)
	assert.Contains(t, ddl, `"street" text`)
	assert.Contains(t, ddl, `"city" varchar(100)`)
}

func TestGenerateDDL_Range(t *testing.T) {
	p := &Project{
		Types: &Types{
			Ranges: []Range{
				{Name: "floatrange", Schema: "public", Subtype: "float8"},
			},
		},
		Schemas: []Schema{{Name: "public"}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, `CREATE TYPE "floatrange" AS RANGE`)
	assert.Contains(t, ddl, "SUBTYPE = float8")
}

// --- Generated columns ---

func TestGenerateDDL_GeneratedColumn(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "products",
				Columns: []Column{
					{Name: "price", Type: "numeric", Precision: 10, Scale: 2},
					{Name: "qty", Type: "integer"},
					{Name: "total", Type: "numeric", Generated: &Generated{Expression: "price * qty", Stored: "true"}},
				},
			}},
		}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, "GENERATED ALWAYS AS (price * qty) STORED")
}

// --- Identity with sequence options ---

func TestGenerateDDL_IdentitySeqOpts(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "events",
				Columns: []Column{
					{Name: "id", Type: "bigint", Nullable: "false", Identity: &Identity{
						Generated: "always",
						Sequence:  &IdentitySeqOpt{Start: 1000, Increment: 10, Cache: 5},
					}},
				},
				PK: &PrimaryKey{Name: "pk_events", Columns: []ColRef{{Name: "id"}}},
			}},
		}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, "GENERATED ALWAYS AS IDENTITY")
	assert.Contains(t, ddl, "START WITH 1000")
	assert.Contains(t, ddl, "INCREMENT BY 10")
	assert.Contains(t, ddl, "CACHE 5")
}

// --- Exclude constraint ---

func TestGenerateDDL_Exclude(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "reservations",
				Columns: []Column{
					{Name: "room_id", Type: "integer"},
					{Name: "during", Type: "tstzrange"},
				},
				Excludes: []Exclude{{
					Name:  "no_overlap",
					Using: "gist",
					Elements: []ExcludeElement{
						{Column: "room_id", With: "="},
						{Column: "during", With: "&&"},
					},
				}},
			}},
		}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, "CONSTRAINT")
	assert.Contains(t, ddl, "EXCLUDE USING gist")
	assert.Contains(t, ddl, `"room_id" WITH =`)
	assert.Contains(t, ddl, `"during" WITH &&`)
}

func TestGenerateDDL_ExcludeOpclass(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name: "reservations",
				Columns: []Column{
					{Name: "room_id", Type: "integer"},
					{Name: "during", Type: "tstzrange"},
				},
				Excludes: []Exclude{{
					Name:  "no_overlap",
					Using: "gist",
					Elements: []ExcludeElement{
						{Column: "room_id", Opclass: "gist_int4_ops", With: "="},
						{Column: "during", With: "&&"},
					},
				}},
			}},
		}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, `"room_id" gist_int4_ops WITH =`)
	assert.Contains(t, ddl, `"during" WITH &&`)
}

// --- Role / RLS / Policy / Grant ---

func TestGenerateDDL_Role(t *testing.T) {
	p := &Project{
		Roles: []Role{{
			Name: "app_user", Login: "true", Createdb: "true",
			InRoles: []InRole{{Name: "base_role"}},
		}},
		Schemas: []Schema{{Name: "public"}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, `CREATE ROLE "app_user" WITH LOGIN`)
	assert.Contains(t, ddl, "CREATEDB")
	assert.Contains(t, ddl, `GRANT "base_role" TO "app_user"`)
}

func TestGenerateDDL_RLS(t *testing.T) {
	p := &Project{
		Schemas: []Schema{{
			Name: "public",
			Tables: []Table{{
				Name:             "documents",
				RowLevelSecurity: "true",
				Columns:          []Column{{Name: "id", Type: "integer"}},
			}},
		}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, "ENABLE ROW LEVEL SECURITY")
}

func TestGenerateDDL_Policy(t *testing.T) {
	p := &Project{
		Policies: []Policy{{
			Name: "own_rows", Schema: "public", Table: "documents",
			Command: "select", To: "app_user",
			Using: &PolicyExpr{Value: "owner_id = current_user_id()"},
		}},
		Schemas: []Schema{{Name: "public", Tables: []Table{{
			Name: "documents", Columns: []Column{{Name: "id", Type: "integer"}},
		}}}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, `CREATE POLICY "own_rows"`)
	assert.Contains(t, ddl, "FOR SELECT")
	assert.Contains(t, ddl, `TO "app_user"`)
	assert.Contains(t, ddl, "USING (owner_id = current_user_id())")
}

func TestGenerateDDL_Grant(t *testing.T) {
	p := &Project{
		Grants: &Grants{
			Grants: []Grant{
				{On: "table", Schema: "public", Name: "documents", Privileges: "select,insert", To: "app_user"},
				{On: "schema", Name: "public", Privileges: "usage", To: "public"},
			},
		},
		Schemas: []Schema{{Name: "public"}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, `GRANT SELECT,INSERT ON TABLE "documents" TO "app_user"`)
	assert.Contains(t, ddl, `GRANT USAGE ON SCHEMA "public" TO PUBLIC`)
}

func TestGenerateDDL_GrantRole(t *testing.T) {
	p := &Project{
		Grants: &Grants{
			GrantRoles: []GrantRole{
				{Role: "admin", To: "app_user", WithInherit: "true"},
			},
		},
		Schemas: []Schema{{Name: "public"}},
	}
	ddl := GenerateDDL(p)
	assert.Contains(t, ddl, `GRANT "admin" TO "app_user"`)
	assert.Contains(t, ddl, "WITH INHERIT TRUE")
}

// --- MatView with no data ---

func TestGenerateDDL_MatViewCircular(t *testing.T) {
	p := &Project{
		Views: &Views{
			MatViews: []MaterializedView{
				{Name: "mv_a", Schema: "public", Query: `SELECT * FROM "mv_b"`},
				{Name: "mv_b", Schema: "public", Query: `SELECT * FROM "mv_a"`},
			},
		},
		Schemas: []Schema{{Name: "public"}},
	}
	ddl := GenerateDDL(p)
	// circular dependency → WITH NO DATA fallback
	assert.Contains(t, ddl, "WITH NO DATA")
}

// --- ERD export ---

func TestToERDSchema(t *testing.T) {
	data, err := os.ReadFile("../format/sql/testdata/chinook.pgd")
	require.NoError(t, err)
	var p Project
	require.NoError(t, xml.Unmarshal(data, &p))

	erd := p.ToERDSchema()
	assert.Len(t, erd.Tables, 11)
	assert.NotEmpty(t, erd.References)

	// check table structure
	for _, tbl := range erd.Tables {
		assert.NotEmpty(t, tbl.Name)
		assert.NotEmpty(t, tbl.Columns)
	}
}

// --- types.go ---

func TestNormalizeType(t *testing.T) {
	tests := []struct{ in, want string }{
		{"int2", "smallint"},
		{"int4", "integer"},
		{"int8", "bigint"},
		{"float4", "real"},
		{"float8", "double precision"},
		{"bool", "boolean"},
		{"character varying", "varchar"},
		{"character", "char"},
		{"bit varying", "varbit"},
		{"timestamp with time zone", "timestamptz"},
		{"timestamp without time zone", "timestamp"},
		{"time with time zone", "timetz"},
		{"time without time zone", "time"},
		{"int4[]", "integer[]"},
		{"bool[]", "boolean[]"},
		{"text", "text"},
		{"jsonb", "jsonb"},
	}
	for _, tt := range tests {
		assert.Equal(t, tt.want, NormalizeType(tt.in), tt.in)
	}
}

func TestNeedsLength(t *testing.T) {
	assert.True(t, NeedsLength("varchar"))
	assert.True(t, NeedsLength("character varying"))
	assert.True(t, NeedsLength("char"))
	assert.True(t, NeedsLength("bit"))
	assert.True(t, NeedsLength("varbit"))
	assert.False(t, NeedsLength("integer"))
	assert.False(t, NeedsLength("text"))
}

func TestColRefsFromNames(t *testing.T) {
	refs := ColRefsFromNames([]string{"a", "b", "c"})
	require.Len(t, refs, 3)
	assert.Equal(t, "a", refs[0].Name)
	assert.Equal(t, "c", refs[2].Name)
}

func TestIsExpression(t *testing.T) {
	assert.True(t, IsExpression("true"))
	assert.True(t, IsExpression("false"))
	assert.True(t, IsExpression("null"))
	assert.True(t, IsExpression("now()"))
	assert.True(t, IsExpression("a + b"))
	assert.False(t, IsExpression("column_name"))
	assert.False(t, IsExpression("my_col"))
}

func TestFKActionFromPGCode(t *testing.T) {
	assert.Equal(t, "cascade", FKActionFromPGCode("c"))
	assert.Equal(t, "set-null", FKActionFromPGCode("n"))
	assert.Equal(t, "set-default", FKActionFromPGCode("d"))
	assert.Equal(t, "restrict", FKActionFromPGCode("r"))
	assert.Equal(t, "no action", FKActionFromPGCode("a"))
	assert.Equal(t, "no action", FKActionFromPGCode("x"))
}

// --- known_types.go ---

func TestStripTypeParams(t *testing.T) {
	assert.Equal(t, "varchar", StripTypeParams("varchar(255)"))
	assert.Equal(t, "numeric", StripTypeParams("numeric(10,2)"))
	assert.Equal(t, "integer", StripTypeParams("integer"))
	assert.Equal(t, "integer", StripTypeParams("integer[]"))
}

func TestIsKnownBuiltinType(t *testing.T) {
	assert.True(t, IsKnownBuiltinType("integer"))
	assert.True(t, IsKnownBuiltinType("varchar"))
	assert.True(t, IsKnownBuiltinType("timestamptz"))
	assert.True(t, IsKnownBuiltinType("jsonb"))
	assert.True(t, IsKnownBuiltinType("uuid"))
	assert.False(t, IsKnownBuiltinType("my_custom_type"))
	assert.False(t, IsKnownBuiltinType("Flag"))
}

// --- Synthetic DDL validation against live PostgreSQL ---

func skipIfNoPG(t *testing.T) {
	t.Helper()
	cmd := exec.Command("psql", "postgres://postgres@localhost:5432/postgres?sslmode=disable", "-c", "SELECT 1")
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		t.Skipf("PostgreSQL not reachable: %v", err)
	}
}

func psqlExec(t *testing.T, dsn, sql string) {
	t.Helper()
	cmd := exec.Command("psql", "--no-psqlrc", dsn, "-c", sql)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("psql failed: %v\n%s", err, out)
	}
}

func psqlFile(t *testing.T, dsn, file string) {
	t.Helper()
	cmd := exec.Command("psql", "--no-psqlrc", dsn, "-f", file)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("psql -f %s failed: %v\n%s", file, err, out)
	}
}

func psqlCount(t *testing.T, dsn, query string) int {
	t.Helper()
	cmd := exec.Command("psql", "--no-psqlrc", dsn, "-tAXc", query)
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("psql count failed: %v", err)
	}
	s := strings.TrimSpace(string(out))
	var n int
	for _, c := range s {
		if c >= '0' && c <= '9' {
			n = n*10 + int(c-'0')
		}
	}
	return n
}

// TestSynthetic_DDL_PostgreSQL loads synthetic.pgd, generates DDL, loads into live PG, verifies objects.
func TestSynthetic_DDL_PostgreSQL(t *testing.T) {
	skipIfNoPG(t)

	baseDSN := "postgres://postgres@localhost:5432/postgres?sslmode=disable"
	dbName := "pgd_test_synthetic"
	dsn := "postgres://postgres@localhost:5432/" + dbName + "?sslmode=disable"

	// Load pgd
	data, err := os.ReadFile("../../docs/testdata/synthetic/schema.pgd")
	require.NoError(t, err)

	var p Project
	require.NoError(t, xml.Unmarshal(data, &p))

	// Generate DDL
	ddl := GenerateDDL(&p)
	require.NotEmpty(t, ddl)

	// Write to temp file
	tmpFile := t.TempDir() + "/synthetic.sql"
	require.NoError(t, os.WriteFile(tmpFile, []byte(ddl), 0644))

	// Create DB
	psqlExec(t, baseDSN, "DROP DATABASE IF EXISTS "+dbName)
	psqlExec(t, baseDSN, "CREATE DATABASE "+dbName)
	defer psqlExec(t, baseDSN, "DROP DATABASE IF EXISTS "+dbName)

	// Load DDL — must succeed without errors
	psqlFile(t, dsn, tmpFile)

	// Verify object counts
	tables := psqlCount(t, dsn, "SELECT count(*) FROM pg_tables WHERE schemaname = 'public'")
	assert.Equal(t, 8, tables, "table count")

	indexes := psqlCount(t, dsn, `SELECT count(*) FROM pg_indexes WHERE schemaname = 'public' AND indexname NOT LIKE '%_pkey'`)
	assert.GreaterOrEqual(t, indexes, 15, "index count (excluding PKs)")

	domains := psqlCount(t, dsn, "SELECT count(*) FROM pg_type WHERE typtype = 'd' AND typnamespace = 'public'::regnamespace")
	assert.Equal(t, 3, domains, "domain count")

	enums := psqlCount(t, dsn, "SELECT count(*) FROM pg_type WHERE typtype = 'e' AND typnamespace = 'public'::regnamespace")
	assert.Equal(t, 2, enums, "enum count")

	functions := psqlCount(t, dsn, "SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname IN ('update_user_search_vector','update_document_search_vector','audit_trigger_func')")
	assert.Equal(t, 3, functions, "function count")

	triggers := psqlCount(t, dsn, "SELECT count(*) FROM pg_trigger t JOIN pg_class c ON t.tgrelid = c.oid JOIN pg_namespace n ON c.relnamespace = n.oid WHERE NOT t.tgisinternal AND n.nspname = 'public'")
	assert.Equal(t, 4, triggers, "trigger count")

	fks := psqlCount(t, dsn, "SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON c.connamespace = n.oid WHERE c.contype = 'f' AND n.nspname = 'public'")
	assert.Equal(t, 9, fks, "FK count")

	checks := psqlCount(t, dsn, "SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON c.connamespace = n.oid WHERE c.contype = 'c' AND n.nspname = 'public'")
	assert.GreaterOrEqual(t, checks, 4, "CHECK constraint count")

	comments := psqlCount(t, dsn, "SELECT count(*) FROM pg_description d JOIN pg_class c ON d.objoid = c.oid JOIN pg_namespace n ON c.relnamespace = n.oid WHERE n.nspname = 'public'")
	assert.GreaterOrEqual(t, comments, 5, "comment count")
}

// TestSynthetic_ReferenceSQL_Match verifies that hand-written reference SQL creates
// the same objects as GenerateDDL output.
func TestSynthetic_ReferenceSQL_Match(t *testing.T) {
	skipIfNoPG(t)

	baseDSN := "postgres://postgres@localhost:5432/postgres?sslmode=disable"

	// Load reference SQL
	refDB := "pgd_test_synthetic_ref"
	refDSN := "postgres://postgres@localhost:5432/" + refDB + "?sslmode=disable"
	psqlExec(t, baseDSN, "DROP DATABASE IF EXISTS "+refDB)
	psqlExec(t, baseDSN, "CREATE DATABASE "+refDB)
	defer psqlExec(t, baseDSN, "DROP DATABASE IF EXISTS "+refDB)
	psqlFile(t, refDSN, "../../docs/testdata/synthetic/schema.sql")

	// Load generated DDL
	genDB := "pgd_test_synthetic_gen"
	genDSN := "postgres://postgres@localhost:5432/" + genDB + "?sslmode=disable"
	psqlExec(t, baseDSN, "DROP DATABASE IF EXISTS "+genDB)
	psqlExec(t, baseDSN, "CREATE DATABASE "+genDB)
	defer psqlExec(t, baseDSN, "DROP DATABASE IF EXISTS "+genDB)

	data, err := os.ReadFile("../../docs/testdata/synthetic/schema.pgd")
	require.NoError(t, err)
	var p Project
	require.NoError(t, xml.Unmarshal(data, &p))
	ddl := GenerateDDL(&p)
	tmpFile := t.TempDir() + "/synthetic_gen.sql"
	require.NoError(t, os.WriteFile(tmpFile, []byte(ddl), 0644))
	psqlFile(t, genDSN, tmpFile)

	// Compare object counts
	countQ := []struct{ name, query string }{
		{"tables", "SELECT count(*) FROM pg_tables WHERE schemaname = 'public'"},
		{"enums", "SELECT count(*) FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typtype = 'e' AND n.nspname = 'public'"},
		{"domains", "SELECT count(*) FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE t.typtype = 'd' AND n.nspname = 'public'"},
		{"FK", "SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON c.connamespace = n.oid WHERE c.contype = 'f' AND n.nspname = 'public'"},
		{"functions", "SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname IN ('update_user_search_vector','update_document_search_vector','audit_trigger_func')"},
		{"triggers", "SELECT count(*) FROM pg_trigger t JOIN pg_class c ON t.tgrelid = c.oid JOIN pg_namespace n ON c.relnamespace = n.oid WHERE NOT t.tgisinternal AND n.nspname = 'public'"},
	}
	for _, q := range countQ {
		ref := psqlCount(t, refDSN, q.query)
		gen := psqlCount(t, genDSN, q.query)
		assert.Equal(t, ref, gen, "%s count mismatch (ref=%d gen=%d)", q.name, ref, gen)
	}
}
